const API_URL=(window.SSINNE_CONFIG||{}).API_URL||'';let TOKEN=localStorage.getItem('ssinne_admin_token')||'';let orderCache=[],productCache=[],liveCache=[],csCache=[],giftCache=[];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s==null?'':s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const money=n=>Number(n||0).toLocaleString('ko-KR')+'원';
async function api(action,p={}){if(!/^https:\/\/script\.google\.com\/macros\/s\//.test(API_URL))throw new Error('config.js에 Apps Script /exec 주소를 입력해주세요.');const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,adminToken:TOKEN,...p})});const j=await r.json();if(!j.success)throw new Error(j.error||'오류가 발생했습니다.');return j}
function toast(m){$('#toast').textContent=m;$('#toast').classList.remove('hidden');setTimeout(()=>$('#toast').classList.add('hidden'),3000)}
function busy(on,m='처리 중입니다...'){$('#busy').classList.toggle('show',on);$('#busyText').textContent=m}
function panel(name){$$('.admin-panel').forEach(x=>x.classList.remove('active'));$('#panel-'+name).classList.add('active');$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));({'orders':loadOrders,'bank':()=>{},'card':loadCards,'live':loadLive,'cs':loadCs,'products':loadProducts,'shipping':loadShipping,'gifts':loadGifts,'settings':loadSettings}[name]||(()=>{}))()}
async function login(){try{busy(true,'로그인 중입니다...');const r=await api('admin_login',{password:$('#adminPassword').value});TOKEN=r.token;localStorage.setItem('ssinne_admin_token',TOKEN);showAdmin()}catch(e){toast(e.message)}finally{busy(false)}}
function showAdmin(){$('#login').classList.add('hidden');$('#adminApp').classList.remove('hidden');panel('orders')}
async function logout(){try{await api('admin_logout')}catch(e){}TOKEN='';localStorage.removeItem('ssinne_admin_token');location.reload()}
async function loadOrders(){try{busy(true,'주문을 불러오는 중입니다...');const r=await api('admin_orders',{query:$('#orderQuery').value,status:$('#orderStatus').value,from:$('#orderFrom').value,to:$('#orderTo').value});orderCache=r.orders;$('#kAll').textContent=r.counts.all;$('#kPaid').textContent=r.counts.paid;$('#kUnpaid').textContent=r.counts.unpaid;$('#kCard').textContent=r.counts.card;renderOrders()}catch(e){toast(e.message)}finally{busy(false)}}
function renderOrders(){const tb=$('#orderTbody');tb.innerHTML=orderCache.map(o=>`<tr><td><input type="checkbox" class="orderCheck" value="${esc(o.orderNo)}"></td><td>${esc(o.date)}</td><td>${esc(o.orderNo)}</td><td>${esc(o.nickname)}</td><td>${esc(o.receiver)}</td><td>${esc(o.phone)}</td><td>${esc((o.items||'').split('\n')[0]||'')}</td><td>${money(o.amount)}</td><td><span class="pill ${o.status==='입금완료'?'green':o.status==='미입금'?'orange':'blue'}">${esc(o.status)}</span></td><td><button class="btn ghost" onclick="openOrder('${encodeURIComponent(o.orderNo)}')">상세</button></td></tr>`).join('')||'<tr><td colspan="10">주문이 없습니다.</td></tr>'}
function selectedOrders(){return $$('.orderCheck:checked').map(x=>x.value)}
async function setOrderStatus(st){const nos=selectedOrders();if(!nos.length)return toast('주문을 선택해주세요.');try{busy(true);await api('admin_update_status',{orderNos:nos,status:st});await loadOrders()}catch(e){toast(e.message)}finally{busy(false)}}
async function deleteOrders(){const nos=selectedOrders();if(!nos.length)return toast('삭제할 주문을 선택해주세요.');if(!confirm(nos.length+'건을 삭제할까요? 재고가 자동 복구됩니다.'))return;try{busy(true,'주문 삭제 및 재고 복구 중...');await api('admin_delete_orders',{orderNos:nos});await loadOrders();toast('삭제했습니다.')}catch(e){toast(e.message)}finally{busy(false)}}
window.openOrder=function(no){no=decodeURIComponent(no);const o=orderCache.find(x=>x.orderNo===no);if(!o)return;$('#orderDetail').innerHTML=`<h2>주문 상세</h2><div class="note"><b>${esc(o.orderNo)}</b><br>${esc(o.nickname)} / ${esc(o.receiver)} / ${esc(o.phone)}<br>${esc(o.address)}<br>${esc(o.memo||'')}</div><h3>구매내역</h3><pre style="white-space:pre-wrap">${esc(o.items)}</pre><div class="toolbar"><button class="btn green" onclick="detailStatus('입금완료','${esc(o.orderNo)}')">입금완료</button><button class="btn" onclick="detailStatus('미입금','${esc(o.orderNo)}')">미입금</button><button class="btn blue" onclick="detailStatus('카드결제','${esc(o.orderNo)}')">카드결제</button><button class="btn red" onclick="detailDelete('${esc(o.orderNo)}')">삭제</button></div>`;$('#orderModal').classList.add('show')}
window.detailStatus=async(st,no)=>{await api('admin_update_status',{orderNos:[no],status:st});$('#orderModal').classList.remove('show');loadOrders()};window.detailDelete=async no=>{if(!confirm('이 주문을 삭제할까요?'))return;await api('admin_delete_orders',{orderNos:[no]});$('#orderModal').classList.remove('show');loadOrders()};

async function loadCards(){try{const r=await api('admin_card_customers');const tb=$('#cardTbody');tb.innerHTML=r.orders.map(o=>`<tr><td><input type="checkbox" class="cardCheck" value="${esc(o.orderNo)}"></td><td>${esc(o.orderNo)}</td><td>${esc(o.nickname)}</td><td>${esc(o.receiver)}</td><td>${esc(o.phone)}</td><td>${money(o.amount)}</td><td>${esc(o.status)}</td></tr>`).join('')||'<tr><td colspan="7">카드결제 주문이 없습니다.</td></tr>'}catch(e){toast(e.message)}}
async function sendCardLink(){const nos=$$('.cardCheck:checked').map(x=>x.value);if(!nos.length)return toast('고객을 선택해주세요.');try{busy(true,'결제링크를 만들고 있습니다...');const r=await api('admin_card_link',{orderNos:nos,sendSms:$('#sendSms').checked});if(r.link){await navigator.clipboard?.writeText(r.link);toast('결제링크를 만들었습니다. '+money(r.amount)+' / 링크도 복사했습니다.')}}catch(e){toast(e.message)}finally{busy(false)}}

async function loadLive(){try{const r=await api('admin_live');liveCache=r.rows;$('#liveTbody').innerHTML=liveCache.map(x=>`<tr><td>${esc(String(x.time).slice(0,19))}</td><td>${esc(x.nickname)}</td><td>${esc(x.chat)}</td><td>${esc(x.productNo)}</td><td>${esc(x.color)}</td><td>${esc(x.size)}</td><td><select onchange="liveChange(${x.row},'status',this.value)"><option ${x.status==='예약'?'selected':''}>예약</option><option ${x.status==='대기'?'selected':''}>대기</option><option ${x.status==='취소'?'selected':''}>취소</option></select></td><td><select onchange="liveChange(${x.row},'orderStatus',this.value)"><option ${x.orderStatus==='미작성'?'selected':''}>미작성</option><option ${x.orderStatus==='작성완료'?'selected':''}>작성완료</option></select></td></tr>`).join('')}catch(e){toast(e.message)}}
window.liveChange=async(row,k,v)=>{try{await api('admin_update_live',{rowNumber:row,[k]:v});toast('반영했습니다.')}catch(e){toast(e.message)}};
async function broadcastAction(a){try{busy(true);const payload=a==='admin_broadcast_start'?{mode:($('#bMode')&&$('#bMode').value)||'new'}:{};const r=await api(a,payload);toast(r.message||'완료했습니다.');await loadLive();if(a==='admin_broadcast_start')await loadProducts()}catch(e){toast(e.message)}finally{busy(false)}}

async function loadProducts(){try{const r=await api('admin_products');productCache=r.products;renderProducts();await loadSnapshots()}catch(e){toast(e.message)}}
function renderProducts(){const tb=$('#productTbody');tb.innerHTML=productCache.map(p=>`<tr><td><input type="checkbox" class="productCheck" value="${esc([p.no,p.color,p.size].map(encodeURIComponent).join('|'))}"></td><td>${esc(p.no)}</td><td>${esc(p.name)}</td><td>${esc(p.color)}</td><td>${esc(p.size)}</td><td>${money(p.sale)}</td><td>${money(p.cost)}</td><td>${p.stock}</td><td>${p.reserved}</td><td style="white-space:pre-wrap">${esc(p.reservedNames)}</td><td>${p.available}</td><td>${esc(p.status)}</td><td><button class="btn ghost" onclick="editProduct('${encodeURIComponent(p.no)}','${encodeURIComponent(p.color)}','${encodeURIComponent(p.size)}')">수정</button></td></tr>`).join('')}
window.editProduct=(no,c,s)=>{no=decodeURIComponent(no);c=decodeURIComponent(c);s=decodeURIComponent(s);const p=productCache.find(x=>x.no===no&&x.color===c&&x.size===s);if(!p)return;$('#pNo').value=p.no;$('#pName').value=p.name;$('#pColor').value=p.color;$('#pSize').value=p.size;$('#pSale').value=p.sale;$('#pCost').value=p.cost;$('#pStock').value=p.stock;$('#pType').value=p.saleType;$('#pImage').value=p.image||'';window.scrollTo({top:0,behavior:'smooth'})}
async function saveProduct(){const product={no:$('#pNo').value,name:$('#pName').value,color:$('#pColor').value,size:$('#pSize').value,sale:$('#pSale').value,cost:$('#pCost').value,stock:$('#pStock').value,saleType:$('#pType').value,image:$('#pImage').value};try{await api('admin_save_product',{product});toast('상품정보를 저장했습니다.');clearProductForm();loadProducts()}catch(e){toast(e.message)}}
function clearProductForm(){['pNo','pName','pColor','pSale','pCost','pStock','pImage'].forEach(id=>$('#'+id).value='');$('#pSize').value='FREE'}
async function deleteProducts(){const keys=$$('.productCheck:checked').map(x=>x.value.split('|').map(decodeURIComponent)).map(x=>[x[0],x[1].toLowerCase().replace(/\s+/g,''),x[2].toLowerCase().replace(/\s+/g,'')].join('|'));if(!keys.length)return toast('상품을 선택해주세요.');if(!confirm('선택 상품을 삭제할까요?'))return;await api('admin_delete_products',{keys});loadProducts()}
async function saveSnapshot(){try{const r=await api('admin_snapshot_save');toast(r.count+'개 상품을 날짜별로 저장했습니다.');loadSnapshots()}catch(e){toast(e.message)}}
async function loadSnapshots(){try{const r=await api('admin_snapshot_list');$('#snapshotList').innerHTML=r.snapshots.map(x=>`<div class="cart-line"><div><b>${esc(x.date)}</b><div class="hint">${x.count}개 상품</div></div><button class="btn ghost" onclick="loadSnapshot('${esc(x.date)}')">불러오기</button></div>`).join('')||'<div class="hint">저장된 날짜가 없습니다.</div>'}catch(e){}}
window.loadSnapshot=async d=>{if(!confirm(d+' 상품정보를 현재 상품정보로 불러올까요?'))return;try{busy(true);await api('admin_snapshot_load',{date:d});await loadProducts();toast('불러왔습니다.')}catch(e){toast(e.message)}finally{busy(false)}};

async function loadGifts(){try{const r=await api('admin_gifts');giftCache=r.rules;$('#giftTbody').innerHTML=giftCache.map(x=>`<tr><td>${esc(x.type)}</td><td>${esc(x.condition)}</td><td>${esc(x.gift)}</td><td><button class="btn red" onclick="deleteGift(${x.rowNumber})">삭제</button></td></tr>`).join('')}catch(e){toast(e.message)}}
async function saveGift(){try{await api('admin_save_gift',{type:$('#gType').value,condition:$('#gCondition').value,gift:$('#gGift').value});$('#gCondition').value='';$('#gGift').value='';loadGifts()}catch(e){toast(e.message)}}window.deleteGift=async r=>{await api('admin_delete_gift',{rowNumber:r});loadGifts()};

async function loadCs(){try{const r=await api('admin_cs_list');csCache=r.cases;$('#csTbody').innerHTML=csCache.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.channelId)}</td><td>${esc(x.nickname)}</td><td>${esc(x.customer)}</td><td>${esc(x.content)}</td><td>${esc(x.type)}</td><td><div class="toolbar"><button class="btn" onclick="csStatus(${x.rowNumber},'접수')">접수</button><button class="btn blue" onclick="csStatus(${x.rowNumber},'진행')">진행</button><button class="btn green" onclick="csStatus(${x.rowNumber},'완료')">오늘완료</button><button class="btn" onclick="csStatus(${x.rowNumber},'보류')">보류</button></div></td></tr>`).join('')}catch(e){toast(e.message)}}
async function saveCs(){try{await api('admin_cs_save',{channelId:$('#csChannel').value,nickname:$('#csNick').value,customer:$('#csCustomer').value,content:$('#csContent').value,type:$('#csType').value});['csChannel','csNick','csCustomer','csContent'].forEach(x=>$('#'+x).value='');loadCs()}catch(e){toast(e.message)}}window.csStatus=async(r,s)=>{await api('admin_cs_update',{rowNumber:r,status:s});loadCs()};

async function loadShipping(){try{$('#shippingMsg').textContent='3PL출고는 고객주문을 기준으로 내품수량 내림차순으로 생성됩니다.'}catch(e){}}
async function rebuild3pl(){try{busy(true);const r=await api('admin_rebuild_3pl');toast('3PL '+r.rows+'건을 생성했습니다.')}catch(e){toast(e.message)}finally{busy(false)}}
async function rebuildSupplier(){try{busy(true);const r=await api('admin_rebuild_supplier');toast('거래처발주 '+r.rows+'행을 생성했습니다.')}catch(e){toast(e.message)}finally{busy(false)}}
async function finalizeShipping(){if(!confirm('송장번호가 반영된 출고완료 주문을 고객주문에서 정리하고 3PL출고를 비울까요?'))return;try{busy(true,'출고완료 주문을 정리하는 중입니다...');const r=await api('admin_finalize_shipping');toast(r.message)}catch(e){toast(e.message)}finally{busy(false)}}
async function exportLotte(){if(typeof XLSX==='undefined')return toast('엑셀 라이브러리를 불러오지 못했습니다.');try{busy(true,'롯데택배 엑셀을 만드는 중입니다...');const r=await api('admin_lotte_export',{date:$('#lotteDate').value});const ws=XLSX.utils.aoa_to_sheet([r.headers,...r.rows]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'sheet1');XLSX.writeFile(wb,r.filename);toast(r.rows.length+'건 다운로드했습니다.')}catch(e){toast(e.message)}finally{busy(false)}}
async function trackingUpload(file){if(!file||typeof XLSX==='undefined')return;const buf=await file.arrayBuffer(),wb=XLSX.read(buf),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:''});const pairs=rows.map(r=>{const keys=Object.keys(r);const ok=keys.find(k=>/주문번호|주문코드|주문/.test(k));const tk=keys.find(k=>/송장번호|운송장|송장/.test(k));return{orderNo:ok?r[ok]:'',tracking:tk?r[tk]:''}}).filter(x=>x.orderNo&&x.tracking);try{const r=await api('admin_apply_tracking',{rows:pairs});toast('송장번호 '+r.updated+'건을 반영했습니다.')}catch(e){toast(e.message)}}
async function bankUpload(file){if(!file||typeof XLSX==='undefined')return;const buf=await file.arrayBuffer(),wb=XLSX.read(buf),ws=wb.Sheets[wb.SheetNames[0]],aoa=XLSX.utils.sheet_to_json(ws,{header:1,defval:''});const deposits=aoa.slice(1).map(r=>({name:r[2],amount:r[6]})).filter(x=>x.name&&Number(String(x.amount).replace(/[^0-9.-]/g,'')));try{busy(true);const res=await api('admin_bank_match',{deposits});$('#bankResults').innerHTML=res.results.map(x=>`<tr><td>${esc(x.name)}</td><td>${money(x.amount)}</td><td>${esc(x.status)}</td><td>${esc(x.orderNo||'')}</td></tr>`).join('');toast('입금 대조를 완료했습니다.')}catch(e){toast(e.message)}finally{busy(false)}}

async function loadSettings(){try{const r=await api('admin_settings_get'),s=r.settings;$('#sVersion').textContent=s.version;$('#sWebApp').value=s.webAppUrl||'';$('#sVideo').value=s.youtubeVideoId||'';$('#sBankName').value=s.bankName||'';$('#sBankAccount').value=s.bankAccount||'';$('#sBankOwner').value=s.bankOwner||'';$('#sBand').value=s.bandUrl||'';$('#sChannel').value=s.channelUrl||'';$('#sCardUrl').value=s.cardFixedUrl||'';$('#sPayUser').value=s.payAppUserId||'';$('#ytStatus').textContent=s.youtubeApiConfigured?'저장됨':'미설정';$('#payStatus').textContent=s.payAppConfigured?'연결됨':'미설정'}catch(e){toast(e.message)}}
async function saveSettings(){const settings={youtubeApiKey:$('#sApiKey').value,youtubeVideoId:$('#sVideo').value,bankName:$('#sBankName').value,bankAccount:$('#sBankAccount').value,bankOwner:$('#sBankOwner').value,bandUrl:$('#sBand').value,channelUrl:$('#sChannel').value,cardFixedUrl:$('#sCardUrl').value,payAppUserId:$('#sPayUser').value,payAppLinkKey:$('#sPayKey').value,payAppLinkVal:$('#sPayVal').value,newAdminPassword:$('#sPassword').value};try{await api('admin_settings_save',{settings});['sApiKey','sPayKey','sPayVal','sPassword'].forEach(x=>$('#'+x).value='');toast('설정을 저장했습니다.');loadSettings()}catch(e){toast(e.message)}}

function bind(){$('#loginBtn').onclick=login;$('#logoutBtn').onclick=logout;$$('.nav button').forEach(b=>b.onclick=()=>panel(b.dataset.panel));$('#orderSearch').onclick=loadOrders;$('#markPaid').onclick=()=>setOrderStatus('입금완료');$('#markUnpaid').onclick=()=>setOrderStatus('미입금');$('#markCard').onclick=()=>setOrderStatus('카드결제');$('#deleteOrders').onclick=deleteOrders;$('#cardSend').onclick=sendCardLink;$('#productSave').onclick=saveProduct;$('#productClear').onclick=clearProductForm;$('#productDelete').onclick=deleteProducts;$('#snapshotSave').onclick=saveSnapshot;$('#giftSave').onclick=saveGift;$('#csSave').onclick=saveCs;$('#csReset').onclick=async()=>{await api('admin_cs_reset_today');loadCs()};$('#build3pl').onclick=rebuild3pl;$('#buildSupplier').onclick=rebuildSupplier;$('#finalizeShipping').onclick=finalizeShipping;$('#lotteDownload').onclick=exportLotte;$('#trackingFile').onchange=e=>trackingUpload(e.target.files[0]);$('#bankFile').onchange=e=>bankUpload(e.target.files[0]);$('#settingsSave').onclick=saveSettings;$('#bStart').onclick=()=>broadcastAction('admin_broadcast_start');$('#bCollect').onclick=()=>broadcastAction('admin_broadcast_collect');$('#bEnd').onclick=()=>broadcastAction('admin_broadcast_end');$('#orderModal').onclick=e=>{if(e.target.id==='orderModal')$('#orderModal').classList.remove('show')}}
document.addEventListener('DOMContentLoaded',()=>{bind();if(TOKEN)showAdmin()});
