const API_URL=(window.SSINNE_CONFIG||{}).API_URL||'';
let TOKEN=localStorage.getItem('ssinne_admin_token')||'';
let orderCache=[],orderActiveFilter='',orderPage=1,orderPageSize=20,orderTotal=0,orderPanelReady=false,orderSelected=new Set(),lookupCache=[],lookupPage=1,lookupPageSize=50,lookupTotal=0,lookupPanelReady=false,productCache=[],productPanelReady=false,giftCache=[],giftPanelReady=false,bankCache=[],bankPendingDeposits=[],bankSelectedFileName='',bankFilter='',bankPage=1,bankPageSize=50,bankOriginalFile=null,bankPreviewHeaders=[],bankPreviewRows=[],optionQueue=[],cardCache=[],cardSendFilter='',cardLoadedAt=0,cardPanelReady=false,shippingPanelReady=false,shippingLoaded=false,livePanelReady=false,csPanelReady=false,settingsPanelReady=false,settingsLoaded=false,pendingCache=[],trackingRows=[],lotteCache=[],lottePanelReady=false,lotteLoaded=false,lottePage=1,lottePageSize=50,lotteTotal=0,lotteSelected=new Set(),lotteCounts={all:0,paid:0,unpaid:0,cardPending:0},combineCache=[],returnCache=[],csCache=[],vipCache=[],adminEdit={order:null,cart:[],editMode:false};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s==null?'':s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=n=>Number(n||0).toLocaleString('ko-KR')+'원';
const norm=s=>String(s||'').trim().toLowerCase().replace(/\s+/g,'').replace(/@/g,'');
const productCode=s=>String(s||'').trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'').slice(0,20);
const pkey=x=>[String(x.productNo||x.no||''),norm(x.color),norm(x.size)].join('|');
async function api(action,p={},timeoutMs=30000){if(!/^https:\/\/script\.google\.com\/macros\/s\//.test(API_URL))throw new Error('config.js에 Apps Script /exec 주소를 입력해주세요.');const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeoutMs);let r;try{r=await fetch(API_URL+'?v='+Date.now(),{method:'POST',headers:{'Content-Type':'text/plain'},body:JSON.stringify({action,adminToken:TOKEN,...p}),signal:c.signal})}catch(e){if(e&&e.name==='AbortError')throw new Error('서버 응답이 지연되고 있습니다. 잠시 후 다시 시도해주세요.');throw new Error('서버 연결이 원활하지 않습니다. 잠시 후 다시 시도해주세요.')}finally{clearTimeout(timer)}if(!r.ok)throw new Error('서버 연결 오류 ('+r.status+')');let j;try{j=JSON.parse(await r.text())}catch(e){throw new Error('서버 응답을 확인할 수 없습니다.')}if(!j.success){if((j.error||'').includes('관리자 로그인이 필요')){TOKEN='';localStorage.removeItem('ssinne_admin_token');showLogin()}throw new Error(j.error||'오류가 발생했습니다.')}return j}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add('hidden'),3200)}
function busy(on,m='처리 중입니다...'){$('#busy').classList.toggle('show',on);$('#busyText').textContent=m}
function localDateText(){const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
function prepareOrdersPanel(){
  if(orderPanelReady)return;orderPanelReady=true;const today=localDateText();
  if(!$('#orderFrom').value&&!$('#orderTo').value){$('#orderFrom').value=today;$('#orderTo').value=today}
  $('#orderTbody').innerHTML='<tr><td colspan="11"><b>조회 버튼을 누르면 필요한 주문만 불러옵니다.</b><div class="hint">처음에는 오늘 날짜가 선택되어 있습니다. 전체기간이 필요하면 날짜를 지우고 조회하세요.</div></td></tr>';
  $('#orderRangeText').textContent='조회 전 · 서버에서 주문을 읽지 않았습니다.';
}
function prepareLookupPanel(){if(lookupPanelReady)return;lookupPanelReady=true;const today=localDateText();if(!$('#lookupFrom').value&&!$('#lookupTo').value){$('#lookupFrom').value=today;$('#lookupTo').value=today}$('#lookupTbody').innerHTML='<tr><td colspan="9"><b>전체주문이력 조회입니다.</b><div class="hint">날짜 또는 검색어를 입력한 뒤 검색을 눌러주세요.</div></td></tr>';$('#lookupRangeText').textContent='조회 전 · 전체주문이력을 읽지 않았습니다.';$('#lookupPager').innerHTML=''}
function prepareCsPanel(){if(csPanelReady)return;csPanelReady=true;$('#csTbody').innerHTML='<tr><td colspan="9">조회 버튼을 눌러 CS 내역을 불러옵니다.</td></tr>'}
function prepareLivePanel(){if(livePanelReady)return;livePanelReady=true;$('#liveTbody').innerHTML='<tr><td colspan="8">기록 불러오기를 눌러 라이브채팅 내역을 확인하세요.</td></tr>'}
function prepareCardPanel(){if(cardPanelReady)return;cardPanelReady=true;$('#cardTbody').innerHTML='<tr><td colspan="9">검색 또는 전체 모아보기를 눌러 카드결제 고객을 불러옵니다.</td></tr>'}
function prepareShippingPanel(){if(shippingPanelReady)return;shippingPanelReady=true;$('#shippingPolicyBadge').textContent='불러오기 전';$('#shippingPolicyBox').innerHTML='<span class="hint">설정 불러오기를 눌러 배송비 정책과 VIP 목록을 확인하세요.</span>';$('#vipTbody').innerHTML='<tr><td colspan="9">설정 불러오기 또는 VIP 검색을 눌러주세요.</td></tr>'}
function prepareProductsPanel(){if(productPanelReady)return;productPanelReady=true;$('#productTbody').innerHTML='<tr><td colspan="13">상품정보 불러오기를 눌러 등록 상품을 확인하세요.</td></tr>';$('#snapshotList').innerHTML='<div class="hint">저장목록 불러오기를 눌러주세요.</div>'}
function prepareGiftsPanel(){if(giftPanelReady)return;giftPanelReady=true;$('#giftTbody').innerHTML='<tr><td colspan="4">사은품 목록 불러오기를 눌러주세요.</td></tr>'}
function prepareSettingsPanel(){if(settingsPanelReady)return;settingsPanelReady=true;$('#ytStatus').textContent='불러오기 전';$('#payStatus').textContent='불러오기 전'}
function resetLotteResultView(message='날짜와 주문상태를 선택한 뒤 조회하기를 눌러주세요.'){
  lotteCache=[];lottePage=1;lotteTotal=0;lotteLoaded=false;lotteSelected.clear();lotteCounts={all:0,paid:0,unpaid:0,cardPending:0};
  ['lAll','lPaid','lWaiting'].forEach(id=>{const el=$('#'+id);if(el)el.textContent='-'});
  if($('#lotteHeaderCheck')){$('#lotteHeaderCheck').checked=false;$('#lotteHeaderCheck').disabled=true}
  if($('#lotteTbody'))$('#lotteTbody').innerHTML=`<tr><td colspan="11"><b>${esc(message)}</b><div class="hint">롯데택배 메뉴에 들어오는 것만으로는 전체주문이력을 읽지 않습니다.</div></td></tr>`;
  if($('#lotteSummary'))$('#lotteSummary').textContent='조회 전 · 전체주문이력을 읽지 않았습니다.';
  if($('#lotteRangeText'))$('#lotteRangeText').textContent='조회 전 · 한 페이지에 50건씩 표시합니다.';
  if($('#lottePager'))$('#lottePager').innerHTML='';
}
function prepareLottePanel(){
  if(lottePanelReady)return;lottePanelReady=true;const today=localDateText();
  if(!$('#lotteFrom').value&&!$('#lotteTo').value){$('#lotteFrom').value=today;$('#lotteTo').value=today}
  if($('#lotteStatus'))$('#lotteStatus').value='전체';
  resetLotteResultView();
  if($('#combineTbody'))$('#combineTbody').innerHTML='<tr><td colspan="7">조회 버튼을 누르면 합배송 후보를 불러옵니다.</td></tr>';
  if($('#combineCount'))$('#combineCount').textContent='조회 전 · 서버에서 데이터를 읽지 않았습니다.';
  if($('#returnTbody'))$('#returnTbody').innerHTML='<tr><td colspan="10">조회 버튼을 누르면 반품·교환 내역을 불러옵니다.</td></tr>';
  if($('#pendingTbody'))$('#pendingTbody').innerHTML='<tr><td colspan="10">조회 버튼을 누르면 미출고 주문을 불러옵니다.</td></tr>';
  if($('#pendingCards'))$('#pendingCards').innerHTML='';
}
function panel(name){
  $$('.admin-panel').forEach(x=>x.classList.remove('active'));$('#panel-'+name)?.classList.add('active');$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));
  ({orders:prepareOrdersPanel,lookup:prepareLookupPanel,cs:prepareCsPanel,live:prepareLivePanel,bank:()=>{},card:prepareCardPanel,shipping:prepareShippingPanel,lotte:()=>{prepareLottePanel();switchLotteTab('download')},products:prepareProductsPanel,gifts:prepareGiftsPanel,settings:prepareSettingsPanel}[name]||(()=>{}))();
}
async function login(){try{busy(true,'로그인 중입니다...');const r=await api('admin_login',{password:$('#adminPassword').value});TOKEN=r.token;localStorage.setItem('ssinne_admin_token',TOKEN);showAdmin()}catch(e){toast(e.message)}finally{busy(false)}}
function showLogin(){$('#adminApp').classList.add('hidden');$('#login').classList.remove('hidden')}
function showAdmin(){$('#login').classList.add('hidden');$('#adminApp').classList.remove('hidden');panel('orders')}
async function logout(){try{await api('admin_logout')}catch(e){}TOKEN='';localStorage.removeItem('ssinne_admin_token');location.reload()}

/* 주문 */
async function loadOrders(extra={}){
  try{
    prepareOrdersPanel();
    if(Object.prototype.hasOwnProperty.call(extra,'filter'))orderActiveFilter=extra.filter||'';
    if(Object.prototype.hasOwnProperty.call(extra,'page'))orderPage=Math.max(1,Number(extra.page)||1);else orderPage=1;
    const source=['불러오기','직접입력'].includes(orderActiveFilter)?orderActiveFilter:'',status=source?'전체':(['입금완료','미입금','카드결제','카드결제대기'].includes(orderActiveFilter)?orderActiveFilter:$('#orderStatus').value);
    busy(true,'필요한 주문만 빠르게 불러오는 중입니다...');
    const r=await api('admin_orders',{query:$('#orderQuery').value,status,source,from:$('#orderFrom').value,to:$('#orderTo').value,page:orderPage,pageSize:orderPageSize},45000);
    orderCache=r.orders||[];orderTotal=Number(r.total||0);orderPage=Number(r.page||orderPage||1);
    $('#kLoad').textContent=r.counts.load||0;$('#kDirect').textContent=r.counts.direct||0;$('#kPaid').textContent=r.counts.paid||0;$('#kUnpaid').textContent=r.counts.unpaid||0;$('#kCard').textContent=r.counts.card||0;$('#kCardPending').textContent=r.counts.cardPending||0;
    $$('.kpi-btn').forEach(b=>b.classList.toggle('active',b.dataset.orderFilter===orderActiveFilter));renderOrders();
  }catch(e){toast(e.message)}finally{busy(false)}
}
function statusClass(s){return s==='입금완료'?'green':s==='카드결제대기'?'blue':s==='카드결제'?'violet':'orange'}
function renderOrders(){
  const pages=Math.max(1,Math.ceil(orderTotal/orderPageSize));orderPage=Math.min(orderPage,pages);const start=(orderPage-1)*orderPageSize,rows=orderCache;
  $('#orderTbody').innerHTML=rows.map(o=>{const grp=o.customerGroupCount>1&&o.customerGroupFirst?`<div class="same-customer-badge">같은고객 ${o.customerGroupCount}건 · 내품 ${Number(o.customerGroupQty||0)}개 · ${money(o.customerGroupAmount||0)}</div>`:'';return`<tr><td><input type="checkbox" class="orderCheck" value="${esc(o.orderNo)}" ${orderSelected.has(o.orderNo)?'checked':''}></td><td>${esc(o.date)}</td><td><b>${esc(o.orderNo)}</b></td><td><div class="customer-cell"><b>${esc(o.nickname)}</b>${grp}</div></td><td><b>${esc(o.receiver)}</b></td><td>${esc(o.phone)}</td><td>${esc((o.items||'').split('\n')[0]||'')}</td><td>${Number(o.qty||0)}</td><td>${money(o.amount)}</td><td><span class="pill ${statusClass(o.status)}">${esc(o.status)}</span></td><td><button class="btn ghost mini" onclick="openOrder('${encodeURIComponent(o.orderNo)}')">상세</button></td></tr>`}).join('')||'<tr><td colspan="11">주문이 없습니다.</td></tr>';
  $$('.orderCheck').forEach(c=>c.onchange=()=>{c.checked?orderSelected.add(c.value):orderSelected.delete(c.value)});const hc=$('#orderHeaderCheck');if(hc){hc.checked=rows.length>0&&rows.every(o=>orderSelected.has(o.orderNo));hc.onchange=()=>{rows.forEach(o=>hc.checked?orderSelected.add(o.orderNo):orderSelected.delete(o.orderNo));renderOrders()}};
  $('#orderRangeText').textContent=orderTotal?`전체 ${orderTotal}건 / 현재 ${start+1}~${Math.min(start+rows.length,orderTotal)}건`:'전체 0건';let html='';if(pages>1){html+=`<button ${orderPage===1?'disabled':''} onclick="goOrderPage(${orderPage-1})">이전</button>`;for(let i=1;i<=pages;i++){if(pages>9&&Math.abs(i-orderPage)>3&&i!==1&&i!==pages){if(i===2||i===pages-1)html+='<span>…</span>';continue}html+=`<button class="${i===orderPage?'active':''}" onclick="goOrderPage(${i})">${i}</button>`}html+=`<button ${orderPage===pages?'disabled':''} onclick="goOrderPage(${orderPage+1})">다음</button>`}$('#orderPager').innerHTML=html;
}
function selectedOrders(){return [...orderSelected]}
async function setOrderStatus(st,nos=selectedOrders()){if(!nos.length)return toast('주문을 선택해주세요.');try{await api('admin_update_status',{orderNos:nos,status:st});const set=new Set(nos);orderCache.forEach(o=>{if(set.has(o.orderNo))o.status=st});orderSelected.clear();renderOrders();toast(st+' 처리했습니다. 필요하면 조회 버튼으로 집계를 새로고침하세요.')}catch(e){toast(e.message)}}
async function deleteOrders(){const nos=selectedOrders();if(!nos.length)return toast('삭제할 주문을 선택해주세요.');if(!confirm(nos.length+'건을 삭제할까요?\n재고·상품정보 요약·라이브 주문서상태도 함께 다시 계산됩니다.'))return;try{busy(true);await api('admin_delete_orders',{orderNos:nos});orderSelected.clear();await loadOrders();toast('삭제했습니다.')}catch(e){toast(e.message)}finally{busy(false)}}
async function exportOrders(){if(typeof XLSX==='undefined')return toast('엑셀 라이브러리를 불러오지 못했습니다.');try{prepareOrdersPanel();busy(true,'조회조건의 전체 주문을 엑셀로 준비하고 있습니다...');const source=['불러오기','직접입력'].includes(orderActiveFilter)?orderActiveFilter:'',status=source?'전체':(['입금완료','미입금','카드결제','카드결제대기'].includes(orderActiveFilter)?orderActiveFilter:$('#orderStatus').value),r=await api('admin_orders',{query:$('#orderQuery').value,status,source,from:$('#orderFrom').value,to:$('#orderTo').value,all:true},60000),rows=(r.orders||[]).map(o=>({'주문일':o.date,'주문번호':o.orderNo,'주문경로':o.source,'입금상태':o.status,'닉네임':o.nickname,'수령인':o.receiver,'연락처':o.phone,'구매내역':o.items,'내품수량':o.qty,'입금금액':o.amount})),ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'주문관리');XLSX.writeFile(wb,'씬느샵_주문관리.xlsx');toast(rows.length+'건을 엑셀로 만들었습니다.')}catch(e){toast(e.message)}finally{busy(false)}}
async function loadLookup(extra={}){try{prepareLookupPanel();if(Object.prototype.hasOwnProperty.call(extra,'page'))lookupPage=Math.max(1,Number(extra.page)||1);else lookupPage=1;busy(true,'전체주문이력에서 주문을 조회하고 있습니다...');const r=await api('admin_history_lookup',{query:$('#lookupQuery').value,from:$('#lookupFrom').value,to:$('#lookupTo').value,page:lookupPage,pageSize:lookupPageSize},45000);lookupCache=r.orders||[];lookupTotal=Number(r.total||0);lookupPage=Number(r.page||lookupPage||1);renderLookup()}catch(e){toast(e.message)}finally{busy(false)}}
function renderLookup(){const pages=Math.max(1,Math.ceil(lookupTotal/lookupPageSize)),start=(lookupPage-1)*lookupPageSize;$('#lookupTbody').innerHTML=lookupCache.map(o=>`<tr><td>${esc(o.date)}</td><td><b>${esc(o.orderNo)}</b>${o.tracking?`<div class="hint">송장 ${esc(o.tracking)}</div>`:''}</td><td>${esc(o.nickname)}</td><td>${esc(o.receiver)}</td><td>${esc(o.phone)}</td><td>${esc((o.items||'').split('\n')[0]||'')}</td><td>${money(o.amount)}</td><td><select class="status-select ${statusClass(o.status)}" onchange="lookupStatus('${encodeURIComponent(o.orderNo)}',this.value)"><option ${o.status==='미입금'?'selected':''}>미입금</option><option ${o.status==='카드결제'?'selected':''}>카드결제</option><option ${o.status==='카드결제대기'?'selected':''}>카드결제대기</option><option ${o.status==='입금완료'?'selected':''}>입금완료</option></select></td><td><button class="btn primary" onclick="openOrder('${encodeURIComponent(o.orderNo)}')">상세보기</button></td></tr>`).join('')||'<tr><td colspan="9">조건에 맞는 전체주문이력이 없습니다.</td></tr>';$('#lookupRangeText').textContent=lookupTotal?`전체 ${lookupTotal}건 / 현재 ${start+1}~${Math.min(start+lookupCache.length,lookupTotal)}건`:'전체 0건';let html='';if(pages>1){html+=`<button ${lookupPage===1?'disabled':''} onclick="goLookupPage(${lookupPage-1})">이전</button>`;for(let i=1;i<=pages;i++){if(pages>11&&Math.abs(i-lookupPage)>4&&i!==1&&i!==pages){if(i===2||i===pages-1)html+='<span>…</span>';continue}html+=`<button class="${i===lookupPage?'active':''}" onclick="goLookupPage(${i})">${i}</button>`}html+=`<button ${lookupPage===pages?'disabled':''} onclick="goLookupPage(${lookupPage+1})">다음</button>`}$('#lookupPager').innerHTML=html}
window.lookupStatus=async(no,status)=>{try{no=decodeURIComponent(no);await api('admin_update_status',{orderNos:[no],status});const x=lookupCache.find(o=>o.orderNo===no);if(x)x.status=status;renderLookup();toast('변경했습니다.')}catch(e){toast(e.message)}};

async function ensureProducts(){if(!productCache.length){const r=await api('admin_products');productCache=r.products||[]}}
window.openOrder=async no=>{no=decodeURIComponent(no);try{busy(true,'주문 상세를 불러오는 중입니다...');const r=await api('admin_order_detail',{orderNo:no});adminEdit.order=r.order;adminEdit.cart=(r.order.editItems||[]).map(x=>({...x}));adminEdit.editMode=false;if(!r.order.historyOnly)await ensureProducts();$('#aoOrderNo').textContent='주문번호 '+r.order.orderNo;$('#orderDetailSummary').innerHTML=`<b>${esc(r.order.nickname)}</b> · ${esc(r.order.phone)}<br>${esc(r.order.receiver)} · ${money(r.order.amount)}${r.order.historyOnly?'<br><span class="pill pink">전체주문이력 · 조회전용</span>':''}${r.order.tracking?`<br><span class="hint">송장번호 ${esc(r.order.tracking)}</span>`:''}`;$('#aoReceiver').value=r.order.receiver||'';$('#aoZip').value=r.order.zip||'';$('#aoAddress').value=r.order.address||'';$('#aoMemo').value=r.order.memo||'';$('#aoStatus').textContent=r.order.status||'';$('#aoProductEditor').classList.add('hidden');$('#aoEditProducts').disabled=!!r.order.historyOnly;$('#aoSave').disabled=!!r.order.historyOnly;$('#aoDelete').disabled=!!r.order.historyOnly;renderAdminCart();if(!r.order.historyOnly)renderAdminCatalog('');else $('#aoCatalog').innerHTML='';$('#orderModal').classList.add('show')}catch(e){toast(e.message)}finally{busy(false)}};
function renderAdminCart(){$('#aoCart').innerHTML=adminEdit.cart.map((x,i)=>`<div class="admin-item-row"><span class="item-no">${esc(x.productNo)}번</span><b>${esc(x.name)}</b><span>${esc(x.color)}</span><span>${esc(x.size)}</span><span>${x.qty}개</span><span>${money(x.price)}</span><strong>${money(x.price*x.qty)}</strong>${adminEdit.editMode?`<div class="qtybox"><button onclick="aoQty(${i},-1)">−</button><b>${x.qty}</b><button onclick="aoQty(${i},1)">+</button></div><button class="btn red mini" onclick="aoRemove(${i})">삭제</button>`:''}</div>`).join('')||'<div class="note">상품이 없습니다.</div>';$('#aoAmount').textContent=money(adminEdit.cart.reduce((s,x)=>s+x.price*x.qty,0))}
window.aoQty=(i,d)=>{adminEdit.cart[i].qty=Math.max(1,Number(adminEdit.cart[i].qty||1)+d);renderAdminCart()};window.aoRemove=i=>{adminEdit.cart.splice(i,1);renderAdminCart()};
function renderAdminCatalog(q){q=norm(q);const list=productCache.filter(p=>!q||norm(String(p.no)).includes(q)||norm(p.name).includes(q)).slice(0,40);$('#aoCatalog').innerHTML=list.map(p=>`<div class="admin-picker-row"><span>${esc(p.no)}번</span><b>${esc(p.name)}</b><span>${esc(p.color)}</span><span>${esc(p.size)}</span><span>${money(p.sale)}</span><small>주문가능 ${Number(p.availableQty??Math.max(0,Number(p.stock||0)-Number(p.orderQty||0)))}</small><button class="btn primary mini" onclick="aoAdd('${encodeURIComponent(p.no)}','${encodeURIComponent(p.color)}','${encodeURIComponent(p.size)}')">추가</button></div>`).join('')||'<div class="hint">검색 결과가 없습니다.</div>'}
window.aoAdd=(no,c,s)=>{no=decodeURIComponent(no);c=decodeURIComponent(c);s=decodeURIComponent(s);const p=productCache.find(x=>String(x.no)===String(no)&&x.color===c&&x.size===s);if(!p)return;const av=Number(p.availableQty??Math.max(0,Number(p.stock||0)-Number(p.orderQty||0))),old=adminEdit.order?.editItems?.find(y=>pkey(y)===pkey(p)),allow=av+Number(old?.qty||0);let x=adminEdit.cart.find(x=>pkey(x)===pkey(p));if((x?.qty||0)>=allow)return toast('주문가능수량은 '+allow+'개입니다.');if(x)x.qty++;else adminEdit.cart.push({productNo:p.no,name:p.name,color:p.color,size:p.size,qty:1,price:p.sale});renderAdminCart()};
async function saveAdminOrder(){if(adminEdit.order?.historyOnly)return toast('전체주문이력의 과거 주문은 조회만 가능합니다.');if(!adminEdit.order||!adminEdit.cart.length)return toast('주문상품을 확인해주세요.');try{busy(true);await api('admin_update_order',{orderNo:adminEdit.order.orderNo,receiver:$('#aoReceiver').value,zip:$('#aoZip').value,address:$('#aoAddress').value,memo:$('#aoMemo').value,items:adminEdit.cart});$('#orderModal').classList.remove('show');toast('수정했습니다.');loadOrders()}catch(e){toast(e.message)}finally{busy(false)}}
async function modalStatus(st){if(!adminEdit.order)return;await api('admin_update_status',{orderNos:[adminEdit.order.orderNo],status:st});$('#aoStatus').textContent=st;toast('변경했습니다.')}
async function modalDelete(){if(adminEdit.order?.historyOnly)return toast('전체주문이력의 과거 주문은 삭제하지 않습니다.');if(!adminEdit.order||!confirm('이 주문을 삭제할까요?'))return;await api('admin_delete_orders',{orderNos:[adminEdit.order.orderNo]});$('#orderModal').classList.remove('show');loadOrders()}

/* 빠른메뉴 */
async function rebuild3pl(){try{busy(true,'3PL을 고객주문 기준으로 새로 만들고 전체주문이력에 반영하는 중입니다...');const r=await api('admin_rebuild_3pl');toast('3PL '+r.rows+'건 생성 · 전체주문이력 동기화 완료');if($('#panel-lotte')?.classList.contains('active'))resetLotteResultView('3PL이 갱신되었습니다. 조회하기를 눌러 최신 목록을 확인하세요.')}catch(e){toast(e.message)}finally{busy(false)}}
async function rebuildSupplier(){try{busy(true,'고객주문 전체를 다시 읽어 거래처발주를 계산하는 중입니다...');const r=await api('admin_rebuild_supplier');toast(r.message||'거래처발주를 새로 계산했습니다.')}catch(e){toast(e.message)}finally{busy(false)}}
async function exportLotte(){if(typeof XLSX==='undefined')return;try{busy(true);const r=await api('admin_lotte_export'),ws=XLSX.utils.aoa_to_sheet([r.headers,...r.rows]),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'ALPS');XLSX.writeFile(wb,r.filename)}catch(e){toast(e.message)}finally{busy(false)}}
async function broadcastEnd(){try{busy(true,'라이브 종료 시각을 저장하고 있습니다...');const r=await api('admin_broadcast_end');toast(r.message||'라이브 종료 처리했습니다.');loadOrders()}catch(e){toast(e.message)}finally{busy(false)}}
async function combineSearch(){try{busy(true,'합배송 가능한 고객을 찾고 있습니다...');const r=await api('admin_combine_list',{from:$('#combineFrom').value,to:$('#combineTo').value,onlyEligible:$('#combineEligibleOnly').checked});combineCache=r.groups||[];$('#combineTbody').innerHTML=combineCache.map(g=>`<tr><td><input class="combineCheck" type="checkbox" value="${esc(g.key)}"></td><td><b>${esc(g.nickname)}</b></td><td>${esc(g.receiver)}</td><td>${g.orderCount}</td><td>${g.qty}</td><td><span class="pill ${g.allPaid?'green':'orange'}">${g.allPaid?'입금완료':'결제확인필요'}</span></td><td><details><summary>주문내용 보기</summary><pre class="detail-pre">${esc(g.itemsText||'')}</pre></details></td></tr>`).join('')||'<tr><td colspan="7">합배송 대상이 없습니다.</td></tr>';$('#combineCount').textContent='합배송 후보 '+combineCache.length+'명';$('#combineHeaderCheck').checked=false}catch(e){toast(e.message)}finally{busy(false)}}
async function combineCopy(){const t=combineCache.map(x=>x.nickname+' / '+x.receiver).join('\n');try{await navigator.clipboard.writeText(t);toast('복사했습니다.')}catch(e){}}
/* 카드결제 - 고객주문 카드결제대기 기준 */
function cardPillClass(s){return s==='발송완료'?'green':s==='재발송필요'?'red':'orange'}
function renderCards(){$('#cardTbody').innerHTML=(cardCache||[]).map(o=>{const sentMeta=o.lastSentAmount?`<div class="hint">최근 ${money(o.lastSentAmount)}${o.lastTaxExcluded?' · 부가세 제외':' · +10%'}</div>`:'',vip=o.vip&&o.vip.isVip?'<span class="pill vip-pill">VIP</span>':'';return`<tr><td><input type="checkbox" class="cardCheck" value="${esc(o.orderNos||o.orderNo)}"></td><td><b>${esc(o.displayOrderNo||o.orderNo)}</b>${o.qty?`<div class="hint">내품 ${Number(o.qty)}개</div>`:''}</td><td>${esc(o.nickname)} ${vip}</td><td>${esc(o.receiver)}</td><td>${esc(o.phone)}</td><td>${money(o.amount)}</td><td><b>${money(o.cardAmount)}</b>${o.vip?.taxExcluded?'<div class="hint">VIP 부가세 제외</div>':''}</td><td><span class="pill ${cardPillClass(o.cardStatus)}">${esc(o.cardStatus||'미발송')}</span>${o.sentAt?`<div class="hint">${esc(o.sentAt)}</div>`:''}${sentMeta}</td><td><select class="status-select ${statusClass(o.paymentStatus)}" onchange="cardStatusChange('${encodeURIComponent(o.orderNos||o.orderNo)}',this.value)"><option ${o.paymentStatus==='카드결제'?'selected':''}>카드결제</option><option ${o.paymentStatus==='카드결제대기'?'selected':''}>카드결제대기</option><option ${o.paymentStatus==='입금완료'?'selected':''}>입금완료</option></select></td></tr>`}).join('')||'<tr><td colspan="9">현재 카드결제 고객이 없습니다.</td></tr>';bindCardChecks()}
function updateCardFilterCounts(c={}){$('#cAll').textContent=c.all||0;$('#cUnsent').textContent=c.unsent||0;$('#cSent').textContent=c.sent||0;$('#cRelink').textContent=c.relink||0;$$('.card-send-filter').forEach(b=>b.classList.toggle('active',(b.dataset.cardSendFilter||'')===cardSendFilter))}
async function loadCards(mode='search',useWarm=false){const q=$('#cardQuery').value.trim();if(mode==='search'&&!q)return toast('검색어를 입력해주세요.');if(useWarm&&cardCache.length&&Date.now()-cardLoadedAt<20000){renderCards();setTimeout(()=>loadCards(mode,false),0);return}let shown=false,t=setTimeout(()=>{shown=true;busy(true,'카드결제 고객을 빠르게 조회하고 있습니다...')},450);try{const r=await api('admin_card_customers',{mode,query:q,sendStatus:cardSendFilter},30000);cardCache=r.orders||[];cardLoadedAt=Date.now();updateCardFilterCounts(r.counts||{});renderCards()}catch(e){toast(e.message)}finally{clearTimeout(t);if(shown)busy(false)}}
function bindCardChecks(){$$('.cardCheck').forEach(x=>x.onchange=updateCardSelectedCount);updateCardSelectedCount()}
function updateCardSelectedCount(){$('#cardSelectedCount').textContent='선택 '+$$('.cardCheck:checked').length+'명'}
async function sendCardLink(){const orderNos=$$('.cardCheck:checked').map(x=>x.value);if(!orderNos.length)return toast('고객을 선택해주세요.');const provider=$('#cardProvider').value,excludeTax=!!$('#cardTaxExclude')?.checked,modeText=excludeTax?'부가세 제외 · 주문금액 그대로':'부가세 10% 포함';if(!confirm(`선택 ${orderNos.length}명에게 ${modeText}으로 카드결제 링크를 생성할까요?`))return;const chunkSize=5,results=[],failures=[];try{busy(true,excludeTax?'부가세 제외 카드링크를 준비하고 있습니다...':'카드링크를 준비하고 있습니다...');for(let i=0;i<orderNos.length;i+=chunkSize){const batch=orderNos.slice(i,i+chunkSize);$('#busyText').textContent=(excludeTax?'부가세 제외 링크 생성 중 ':'카드링크 생성 중 ')+Math.min(i+batch.length,orderNos.length)+' / '+orderNos.length+'명';try{const r=await api('admin_card_link',{orderNos:batch,provider,excludeTax},45000);results.push(...(r.results||[]));failures.push(...(r.failures||[]))}catch(e){batch.forEach(no=>failures.push({orderNo:no,error:e.message||String(e)}))}}if(results.length){const text=results.map(x=>`${x.nickname||x.receiver} ${money(x.amount)}${x.taxExcluded?' (부가세 제외)':''}\n${x.link}`).join('\n\n');try{await navigator.clipboard.writeText(text);toast((excludeTax?'부가세 제외 ':'')+'카드결제 링크 '+results.length+'건을 생성하고 복사했습니다.')}catch(e){toast('링크 '+results.length+'건 생성 완료')}}if(failures.length)alert('실패 '+failures.length+'건\n\n'+failures.map(x=>x.orderNo+': '+x.error).join('\n'));await loadCards('all')}catch(e){toast(e.message)}finally{busy(false)}}
window.cardStatusChange=async(no,status)=>{try{await api('admin_update_status',{orderNos:decodeURIComponent(no).split(',').map(x=>x.trim()).filter(Boolean),status});toast('변경했습니다.');loadCards('all')}catch(e){toast(e.message)}};

/* 라이브 */
async function loadLive(){try{const r=await api('admin_live');$('#liveTbody').innerHTML=(r.rows||[]).map(x=>`<tr><td>${esc(x.time)}</td><td>${esc(x.nickname)}</td><td>${esc(x.chat||x.text)}</td><td>${esc(x.productNo)}</td><td>${esc(x.color)}</td><td>${esc(x.size)}</td><td><select class="input compact-select" onchange="liveTypeChange(${Number(x.row||0)},this.value)"><option ${x.type==='예약'?'selected':''}>예약</option><option ${x.type==='대기'?'selected':''}>대기</option><option ${x.type==='취소'?'selected':''}>취소</option></select></td><td><span class="pill ${x.orderStatus==='작성완료'?'green':x.orderStatus==='취소'?'red':'gray'}">${esc(x.orderStatus||'미작성')}</span></td></tr>`).join('')||'<tr><td colspan="8">주문성 댓글이 없습니다.</td></tr>'}catch(e){toast(e.message)}}
window.liveTypeChange=async(row,type)=>{try{await api('admin_update_live',{rowNumber:row,type});toast(type+'로 변경했습니다.');await loadLive();if($('#panel-products')?.classList.contains('active'))loadProducts()}catch(e){toast(e.message)}};
async function broadcastStart(){ $('#startModal').classList.add('show') }
async function broadcastStartMode(mode){try{busy(true,mode==='new'?'상품정보까지 비우고 새 라이브를 시작합니다...':'현재 상품정보를 유지하고 새 라이브를 시작합니다...');const r=await api('admin_broadcast_start',{mode});toast(r.message||'라이브를 시작했습니다.');$('#startModal').classList.remove('show');productCache=[];loadLive()}catch(e){toast(e.message)}finally{busy(false)}}
async function collectLive(){try{busy(true,'주문성 댓글만 가져오는 중입니다...');const r=await api('admin_broadcast_collect');toast(r.message);loadLive()}catch(e){toast(e.message)}finally{busy(false)}}
async function saveLiveVideo(){try{await api('admin_settings_save',{settings:{youtubeVideoId:$('#liveVideoQuick').value}});toast('저장했습니다.');$('#liveLinkModal').classList.remove('show')}catch(e){toast(e.message)}}

/* 상품 */
async function loadProducts(){try{busy(true,'상품정보를 불러오고 있습니다...');const r=await api('admin_products');productCache=r.products||[];renderProducts()}catch(e){toast(e.message)}finally{busy(false)}}
function renderProducts(){$('#productTbody').innerHTML=productCache.map(p=>`<tr><td><input type="checkbox" class="productCheck" value="${encodeURIComponent(p.no)}|${encodeURIComponent(p.color)}|${encodeURIComponent(p.size)}"></td><td>${esc(p.no)}</td><td>${esc(p.name)}</td><td>${esc(p.color)}</td><td>${esc(p.size)}</td><td>${money(p.sale)}</td><td>${money(p.cost)}</td><td>${p.stock}</td><td><span class="pill ${p.status==='품절'?'red':'green'}">${esc(p.status)}</span></td><td>${p.commentReserveQty||0}</td><td>${p.orderQty||0}</td><td><b class="available-qty ${Number(p.availableQty||0)<=0?'soldout':''}">${Number(p.availableQty||0)}</b></td><td><button class="btn ghost" onclick="editProduct('${encodeURIComponent(p.no)}','${encodeURIComponent(p.color)}','${encodeURIComponent(p.size)}')">수정</button></td></tr>`).join('')||'<tr><td colspan="13">등록된 상품이 없습니다.</td></tr>'}
window.editProduct=(no,c,s)=>{no=decodeURIComponent(no);c=decodeURIComponent(c);s=decodeURIComponent(s);const p=productCache.find(x=>String(x.no)===String(no)&&x.color===c&&x.size===s);if(!p)return;$('#pNo').value=p.no;$('#pName').value=p.name;$('#pColor').value=p.color;$('#pSize').value=p.size;$('#pSale').value=p.sale;$('#pCost').value=p.cost;$('#pStock').value=p.stock;optionQueue=[];renderOptionQueue();window.scrollTo({top:0,behavior:'smooth'})};
function optionAdd(){const color=$('#pColor').value.trim(),size=$('#pSize').value.trim()||'FREE',stock=Number($('#pStock').value||0);if(!color)return toast('칼라를 입력해주세요.');optionQueue.push({color,size,stock});$('#pColor').value='';$('#pSize').value='FREE';renderOptionQueue()}
function renderOptionQueue(){$('#optionList').innerHTML=optionQueue.map((x,i)=>`<span class="pill">${esc(x.color)} / ${esc(x.size)} / 재고 ${x.stock} <button onclick="removeOption(${i})">×</button></span>`).join(' ')}window.removeOption=i=>{optionQueue.splice(i,1);renderOptionQueue()};
async function saveProduct(){const base={no:productCode($('#pNo').value),name:$('#pName').value,sale:$('#pSale').value,cost:$('#pCost').value},opts=optionQueue.length?optionQueue:[{color:$('#pColor').value,size:$('#pSize').value,stock:$('#pStock').value}];$('#pNo').value=base.no;if(!base.no||!base.name)return toast('상품번호와 상품명을 입력해주세요.');try{busy(true,'상품정보를 한 번에 저장하고 있습니다...');await api('admin_save_products',{products:opts.map(o=>({...base,...o}))},30000);clearProductForm();productCache=[];await loadProducts();toast('저장했습니다.')}catch(e){toast(e.message)}finally{busy(false)}}
function clearProductForm(){['pNo','pName','pColor','pSale','pCost','pStock'].forEach(id=>$('#'+id).value='');$('#pSize').value='FREE';optionQueue=[];renderOptionQueue()}
async function deleteProducts(){const keys=$$('.productCheck:checked').map(x=>x.value.split('|').map(decodeURIComponent)).map(x=>[x[0],norm(x[1]),norm(x[2])].join('|'));if(!keys.length)return toast('상품을 선택해주세요.');if(!confirm('선택 상품을 삭제할까요?'))return;await api('admin_delete_products',{keys});productCache=[];loadProducts()}
async function deleteAllProducts(){if(!confirm('등록된 상품정보를 모두 삭제할까요?\n과거 주문기록은 삭제되지 않습니다.'))return;await api('admin_delete_products',{all:true});productCache=[];loadProducts()}
async function saveSnapshot(){const vendor=$('#snapshotVendor').value.trim(),date=$('#snapshotDate').value||new Date().toISOString().slice(0,10);if(!vendor)return toast('업체명을 입력해주세요.');try{const r=await api('admin_snapshot_save',{date,vendorName:vendor});toast(r.count+'개 저장했습니다.');loadSnapshots()}catch(e){toast(e.message)}}
async function loadSnapshots(){try{const r=await api('admin_snapshot_list');$('#snapshotList').innerHTML=(r.snapshots||[]).map(x=>`<div class="cart-line"><div><b>${esc(x.date)} · ${esc(x.vendorName)}</b><div class="hint">${x.count}개</div></div><button class="btn softpink" onclick="loadSnapshot('${esc(x.date)}','${encodeURIComponent(x.vendorName)}')">불러오기</button></div>`).join('')||'<div class="hint">저장된 정보가 없습니다.</div>'}catch(e){}}
window.loadSnapshot=async(date,vendor)=>{if(!confirm(date+' 상품정보를 현재 상품정보로 불러올까요?'))return;await api('admin_snapshot_load',{date,vendorName:decodeURIComponent(vendor)});productCache=[];loadProducts()};async function loadSnapshotByDate(){const date=$('#snapshotDate').value;if(!date)return toast('날짜를 선택해주세요.');await api('admin_snapshot_load',{date});productCache=[];loadProducts()}

/* 사은품 */
async function loadGifts(){try{const r=await api('admin_gifts');giftCache=r.rules||[];$('#giftTbody').innerHTML=giftCache.map(x=>`<tr><td>${esc(x.type)}</td><td>${esc(x.condition)}</td><td>${esc(x.gift)}</td><td><button class="btn red" onclick="deleteGift(${x.rowNumber})">삭제</button></td></tr>`).join('')||'<tr><td colspan="4">등록된 사은품이 없습니다.</td></tr>'}catch(e){toast(e.message)}}
async function saveGift(){await api('admin_save_gift',{type:$('#gType').value,condition:$('#gCondition').value,gift:$('#gGift').value});$('#gCondition').value='';$('#gGift').value='';loadGifts()}window.deleteGift=async r=>{await api('admin_delete_gift',{rowNumber:r});loadGifts()};async function applyGifts(){try{busy(true);const r=await api('admin_apply_gifts');toast('3PL '+r.rows+'건에 사은품 규칙을 적용했습니다.')}catch(e){toast(e.message)}finally{busy(false)}}

/* 입금 */
function findBankHeaderRow(aoa){for(let i=0;i<Math.min(30,aoa.length);i++){const row=(aoa[i]||[]).map(x=>String(x||'').trim());if(row.includes('적요')&&row.includes('거래 금액'))return i;if(row.includes('입금자명')&&row.includes('입금금액'))return i}return-1}
async function bankUpload(file){bankPendingDeposits=[];bankSelectedFileName='';bankOriginalFile=file||null;bankPreviewHeaders=[];bankPreviewRows=[];$('#bankStart').disabled=true;if(!file||typeof XLSX==='undefined')return;try{const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{cellDates:false}),ws=wb.Sheets[wb.SheetNames[0]],aoa=XLSX.utils.sheet_to_json(ws,{header:1,defval:''}),hi=findBankHeaderRow(aoa);if(hi<0)throw new Error('거래내역 헤더(적요/거래 금액)를 찾지 못했습니다.');const h=aoa[hi].map(x=>String(x||'').trim()),nameI=h.indexOf('적요')>=0?h.indexOf('적요'):h.indexOf('입금자명'),amtI=h.indexOf('거래 금액')>=0?h.indexOf('거래 금액'):h.indexOf('입금금액'),typeI=h.indexOf('거래 유형');bankPreviewHeaders=h;bankPreviewRows=aoa.slice(hi+1).filter(r=>r.some(v=>String(v||'').trim()));renderBankPreview();bankCache=[];bankFilter='';bankPage=1;renderBank();bankPendingDeposits=aoa.slice(hi+1).filter(r=>typeI<0||String(r[typeI]||'').trim()==='입금').map(r=>({name:String(r[nameI]||'').replace(/^'+/,'').trim(),amount:Number(String(r[amtI]||'').replace(/[^0-9.-]/g,''))})).filter(x=>x.name&&Number.isFinite(x.amount)&&x.amount>0);bankSelectedFileName=file.name;$('#bankFileStatus').textContent=bankPendingDeposits.length?`${file.name} · 입금 ${bankPendingDeposits.length}건 준비됨`:`${file.name} · 매칭할 입금내역이 없습니다.`;$('#bankFileMeta').textContent=`업로드 ${new Date().toLocaleString('ko-KR')} · 원본 ${bankPreviewRows.length}행`;$('#bankStart').disabled=!bankPendingDeposits.length;if(bankPendingDeposits.length)await bankStartMatch()}catch(e){const msg=/password|encrypt|CFB|Unsupported|File is password/i.test(String(e&&e.message||e))?'암호가 설정된 엑셀입니다. 비밀번호를 해제한 뒤 다시 올려주세요.':(e.message||'파일을 다시 확인해주세요.');$('#bankFileStatus').textContent=msg;toast(msg)}}
async function bankStartMatch(){if(!bankPendingDeposits.length)return toast('먼저 거래내역 파일을 선택해주세요.');try{busy(true,'거래내역을 주문과 매칭하고 있습니다...');const r=await api('admin_bank_match',{deposits:bankPendingDeposits});bankCache=r.results||[];bankFilter='';bankPage=1;renderBank();switchBankTab('match');$('#bankFileStatus').textContent=`${bankSelectedFileName} · ${bankCache.length}건 매칭 완료`;toast('입금 대조를 완료했습니다.')}catch(e){toast(e.message)}finally{busy(false)}}
function bankCounts(){return{all:bankCache.length,paid:bankCache.filter(x=>x.status==='입금완료').length,missing:bankCache.filter(x=>x.status==='주문미발견').length,mismatch:bankCache.filter(x=>x.status==='금액불일치').length}}
function bankFilteredEntries(){return bankCache.map((x,i)=>({x,i})).filter(({x})=>!bankFilter||x.status===bankFilter)}
function bankPagerHtml(pages){if(pages<=1)return'';let html=`<button ${bankPage===1?'disabled':''} onclick="goBankPage(${bankPage-1})">이전</button>`;for(let i=1;i<=pages;i++){if(pages>11&&Math.abs(i-bankPage)>4&&i!==1&&i!==pages){if(i===2||i===pages-1)html+='<span>…</span>';continue}html+=`<button class="${i===bankPage?'active':''}" onclick="goBankPage(${i})">${i}</button>`}html+=`<button ${bankPage===pages?'disabled':''} onclick="goBankPage(${bankPage+1})">다음</button>`;return html}
function renderBank(){
  const c=bankCounts();$('#bankAllCount').textContent=c.all;$('#bankPaidCount').textContent=c.paid;$('#bankMissingCount').textContent=c.missing;$('#bankMismatchCount').textContent=c.mismatch;
  $$('.bank-filter').forEach(b=>b.classList.toggle('active',(b.dataset.bankFilter||'')===bankFilter));
  const arr=bankFilteredEntries(),total=arr.length,pages=Math.max(1,Math.ceil(total/bankPageSize));bankPage=Math.min(Math.max(1,bankPage),pages);const start=(bankPage-1)*bankPageSize,pageRows=arr.slice(start,start+bankPageSize);
  $('#bankResults').innerHTML=pageRows.map(({x,i})=>`<tr><td><input type="checkbox" class="bankCheck" value="${i}"></td><td><b>${esc(x.name)}</b></td><td>${money(x.amount)}</td><td><b>${esc(x.nickname||'-')}</b><div class="hint">${esc(x.receiver||'')}</div></td><td>${x.orderAmount?money(x.orderAmount):'-'}</td><td><span class="pill ${x.status==='입금완료'?'green':x.status==='금액불일치'?'red':'orange'}">${esc(x.status)}</span><div class="hint">${esc(x.reason||'')}</div>${x.orderNo?`<small>${esc(x.orderNo)}</small>`:''}</td><td>${(!x.orderNo&&x.candidates&&x.candidates.length)?`<select class="input bank-candidate" id="bankCandidate${i}"><option value="">후보 주문 선택</option>${x.candidates.map(c=>`<option value="${esc(c.no)}">${esc(c.no)} · ${esc(c.nickname||c.receiver)} · ${money(c.amount)}</option>`).join('')}</select>`:''}<select class="input" onchange="bankStatusChange(${i},this.value)" ${x.orderNo||(x.candidates&&x.candidates.length)?'':'disabled'}><option ${(x.paymentStatus||x.status)==='입금완료'?'selected':''}>입금완료</option><option ${x.paymentStatus==='미입금'?'selected':''}>미입금</option><option ${x.paymentStatus==='카드결제'?'selected':''}>카드결제</option><option ${x.paymentStatus==='카드결제대기'?'selected':''}>카드결제대기</option></select></td><td><button class="btn red mini" onclick="bankDeleteOne(${i})">삭제</button></td></tr>`).join('')||'<tr><td colspan="8">대조 결과가 없습니다.</td></tr>';
  $('#bankHeaderCheck').checked=false;
  if($('#bankRangeText'))$('#bankRangeText').textContent=total?`${bankFilter||'전체'} ${total}건 / 현재 ${start+1}~${Math.min(start+pageRows.length,total)}건 / 50건씩 보기`:`${bankFilter||'전체'} 0건 / 50건씩 보기`;
  if($('#bankPager'))$('#bankPager').innerHTML=bankPagerHtml(pages);
}
window.goBankPage=p=>{const next=Math.max(1,Number(p)||1);if(next===bankPage)return;bankPage=next;renderBank();const view=$('#bankMatchView');if(view)view.scrollIntoView({behavior:'smooth',block:'start'})};
window.bankStatusChange=async(i,status)=>{const x=bankCache[i];if(!x)return;let no=x.orderNo;if(!no){no=$('#bankCandidate'+i)?.value||'';if(!no)return toast('먼저 후보 주문을 선택해주세요.');x.orderNo=no;const c=(x.candidates||[]).find(v=>v.no===no);if(c)x.nickname=c.nickname||x.nickname;}try{await api('admin_bank_status',{orderNo:no,status});x.paymentStatus=status;if(status==='입금완료'){x.status='입금완료';x.reason=(x.reason||'')+' · 관리자 수동확인 완료';}renderBank();toast('변경했습니다.')}catch(e){toast(e.message)}};
window.bankDeleteOne=i=>{bankCache.splice(i,1);renderBank()};
function bankDeleteSelected(){const idx=$$('.bankCheck:checked').map(x=>Number(x.value)).filter(Number.isFinite).sort((a,b)=>b-a);if(!idx.length)return toast('삭제할 결과를 선택해주세요.');if(!confirm(idx.length+'건의 대조 결과를 목록에서 삭제할까요?\n고객주문 원본은 삭제되지 않습니다.'))return;idx.forEach(i=>bankCache.splice(i,1));renderBank();toast('선택한 결과를 삭제했습니다.')}
function bankReset(){bankCache=[];bankPendingDeposits=[];bankSelectedFileName='';bankFilter='';bankPage=1;bankOriginalFile=null;bankPreviewHeaders=[];bankPreviewRows=[];$('#bankFile').value='';$('#bankFileStatus').textContent='파일을 선택해주세요.';$('#bankFileMeta').textContent='';$('#bankStart').disabled=true;renderBank();renderBankPreview()}
/* 미출고 - 전체주문이력에서 송장번호가 없는 주문만 */
async function loadPending(){try{busy(true,'미출고 주문을 불러오는 중입니다...');const r=await api('admin_pending_list',{query:$('#pendingQuery')?.value||'',from:$('#pendingFrom')?.value||'',to:$('#pendingTo')?.value||'',status:$('#pendingStatus')?.value||'전체'});pendingCache=r.rows||[];renderPending()}catch(e){toast(e.message)}finally{busy(false)}}
function pendingItemPreview(x){const lines=(x.items||'').split('\n').filter(Boolean);return esc(lines.slice(0,2).join(' / '))+(lines.length>2?`<div class="hint">외 ${lines.length-2}줄</div>`:'')}
function renderPending(){const rows=pendingCache||[];$('#pendingTbody').innerHTML=rows.map(x=>`<tr><td><input class="pendingCheck" type="checkbox" value="${x.rowNumber}"></td><td><b>${esc(x.orderNo)}</b><div class="hint">${esc(x.date)}</div></td><td>${esc(x.nickname)}</td><td>${esc(x.receiver)}</td><td>${esc(x.phone)}</td><td class="pending-items">${pendingItemPreview(x)}<div class="hint">내품 ${x.qty||0}개</div></td><td><span class="pill ${statusClass(x.paymentStatus)}">${esc(x.paymentStatus)}</span></td><td><input id="pr${x.rowNumber}" class="input pending-reason-input" value="${esc(x.reason)}" placeholder="예: 거래처 입고 지연"></td><td><input id="pe${x.rowNumber}" class="input pending-date-input" type="date" value="${esc(x.expectedDate)}"></td><td><button class="btn primary mini" onclick="savePending(${x.rowNumber},'')">저장</button></td></tr>`).join('')||'<tr><td colspan="10">현재 미출고 주문이 없습니다.</td></tr>';$('#pendingCards').innerHTML='';if($('#pendingHeaderCheck'))$('#pendingHeaderCheck').checked=false}
window.savePending=async(row,prefix)=>{try{const pre=prefix||'',reason=$('#'+pre+'pr'+row)?.value||'',expectedDate=$('#'+pre+'pe'+row)?.value||'';await api('admin_pending_update',{rowNumber:row,reason,expectedDate});toast('미출고 정보를 저장했습니다.');await loadPending()}catch(e){toast(e.message)}};
function selectedPendingRows(){return [...new Set($$('.pendingCheck:checked').map(x=>Number(x.value)).filter(Number.isFinite))]}
function writeXlsx(r,sheetName='ALPS'){if(typeof XLSX==='undefined')return toast('엑셀 라이브러리를 불러오지 못했습니다.');const ws=XLSX.utils.aoa_to_sheet([r.headers,...r.rows]),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,sheetName);XLSX.writeFile(wb,r.filename)}
async function pendingLotte(){const rows=selectedPendingRows();if(!rows.length)return toast('다시 송장을 출력할 미출고 주문을 선택해주세요.');try{busy(true,'미출고 롯데택배 파일을 만드는 중입니다...');const r=await api('admin_pending_lotte_export',{rows});if(!r.rows?.length)return toast('출력 가능한 미출고 건이 없습니다.');writeXlsx(r);toast(r.rows.length+'줄의 롯데택배 파일을 만들었습니다.')}catch(e){toast(e.message)}finally{busy(false)}}

/* 롯데 송장 업로드 - V7.0.0 안전매칭 */
function findTrackingHeader(aoa){
  for(let i=0;i<Math.min(40,aoa.length);i++){
    const h=(aoa[i]||[]).map(x=>String(x||'').trim()),find=re=>h.findIndex(x=>re.test(x.replace(/\s+/g,'')));
    const oi=find(/^(주문번호|접수번호|고객주문번호|주문관리번호)$/),ti=find(/^(운송장번호|송장번호|택배운송장번호)$/),ri=find(/^(받는사람|받는분|받는사람명|수령인|수취인|수취인명|수하인|수하인명|수화주)$/),pi=find(/^(전화번호1|전화번호|연락처|휴대폰|휴대전화|휴대전화번호|핸드폰|핸드폰번호|수령인연락처|수취인연락처|수하인전화번호)$/);
    if(ti>=0&&(oi>=0||(ri>=0&&pi>=0)))return{i,oi,ti,ri,pi};
  }
  return null;
}
function resetTrackingCounts(total=0){$('#trackMatched').textContent='0';$('#trackDuplicate').textContent='0';$('#trackReview').textContent='0';$('#trackMissing').textContent='0';$('#trackTotal').textContent=String(total||0)}
function trackingPhoneText(v){let s=String(v??'').trim(),d=s.replace(/\D/g,'');if(d.length===10&&d.startsWith('10'))d='0'+d;return d||s}
async function trackingRead(file){
  trackingRows=[];$('#trackingTbody').innerHTML='';resetTrackingCounts(0);if(!file)return;
  try{
    const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{cellDates:false}),ws=wb.Sheets[wb.SheetNames[0]],aoa=XLSX.utils.sheet_to_json(ws,{header:1,defval:''}),h=findTrackingHeader(aoa);
    if(!h)throw new Error('송장번호 열과 주문번호 또는 수령인·연락처 열을 찾지 못했습니다.');
    trackingRows=aoa.slice(h.i+1).map((r,n)=>({rowNo:h.i+n+2,orderNo:h.oi>=0?String(r[h.oi]||'').trim():'',receiver:h.ri>=0?String(r[h.ri]||'').trim():'',phone:h.pi>=0?trackingPhoneText(r[h.pi]):'',tracking:String(r[h.ti]||'').replace(/[^0-9-]/g,'').trim(),result:'준비',matchMethod:'',matchedOrderNos:[],detail:''})).filter(x=>x.tracking&&(x.orderNo||(x.receiver&&x.phone)));
    $('#trackingStatus').textContent=`${file.name} · ${trackingRows.length}건 준비됨 · 수령인/연락처 ${h.ri>=0&&h.pi>=0?'확인 가능':'열 없음'}`;resetTrackingCounts(trackingRows.length);renderTrackingRows();
  }catch(e){trackingRows=[];resetTrackingCounts(0);$('#trackingStatus').textContent=e.message;toast(e.message)}
}
async function trackingApply(){
  if(!trackingRows.length)return toast('먼저 롯데 송장 결과 엑셀을 선택해주세요.');
  try{
    busy(true,'송장번호를 안전하게 대조하고 있습니다...');
    const r=await api('admin_apply_tracking',{items:trackingRows},60000),c=r.counts||{};trackingRows=r.results||trackingRows;
    $('#trackMatched').textContent=c.matched||0;$('#trackDuplicate').textContent=c.duplicate||0;$('#trackReview').textContent=c.review||0;$('#trackMissing').textContent=c.unmatched||0;$('#trackTotal').textContent=c.total??trackingRows.length;
    $('#trackingStatus').textContent=`매칭완료 ${c.matched||0} · 중복 ${c.duplicate||0} · 확인필요 ${c.review||0} · 미매칭 ${c.unmatched||0} · 실제 갱신 ${r.updated||0}행`;
    renderTrackingRows();toast(`송장번호 대조 완료 · 매칭 ${c.matched||0}건`);
  }catch(e){toast(e.message)}finally{busy(false)}
}
/* 배송비 / VIP */
async function loadShippingPolicy(){try{const r=await api('admin_shipping_policy',{},30000),on=!!r.freeShippingEvent;shippingLoaded=true;$('#shippingPolicyBadge').textContent=on?'무료배송 이벤트 적용중':'기본 배송비 정책';$('#shippingPolicyBadge').className='pill '+(on?'green':'blue');$('#shipBasic').value=Number(r.shipping||4000);$('#shipIsland').value=Number(r.islandShipping||7000);$('#shipThreshold').value=Number(r.freeShippingThreshold||200000);$('#shipCardRate').value=String(Number(r.cardExtraRate??0.10));$('#shipFreeEvent').checked=on;$('#shippingPolicyBox').innerHTML=on?'<strong>🚚 무료배송 이벤트 적용중</strong><br><span>현재 주문과 새 주문의 배송비가 0원입니다. VIP 개별 혜택도 계속 유지됩니다.</span>':`<strong>기본 정책 사용중</strong><br><span>${money(r.freeShippingThreshold||200000)} 이상 무료 · 일반 ${money(r.shipping||4000)} · 제주/도서산간 ${money(r.islandShipping||7000)} · VIP ${Number(r.vipCount||0)}명</span>`}catch(e){toast(e.message)}}
async function saveShippingSettings(){if(!shippingLoaded)return toast('먼저 설정 불러오기를 눌러 현재 배송비 설정을 확인해주세요.');const payload={shipping:Number($('#shipBasic').value||0),islandShipping:Number($('#shipIsland').value||0),freeShippingThreshold:Number($('#shipThreshold').value||0),cardExtraRate:Number($('#shipCardRate').value||0),freeShippingEvent:$('#shipFreeEvent').checked};if(!confirm('배송비/VIP 기본 정책을 저장하고 현재 고객주문 금액을 다시 계산할까요?'))return;try{busy(true,'배송비 정책을 저장하고 주문금액을 다시 계산하고 있습니다...');const r=await api('admin_shipping_settings_save',payload,60000);await loadShippingPolicy();toast(`배송비 설정 저장 완료 · ${Number(r.changed||0)}건 금액 갱신${Number(r.relink||0)?` · 카드링크 재발송필요 ${Number(r.relink)}건`:''}`)}catch(e){toast(e.message)}finally{busy(false)}}
async function applyShippingEvent(free){$('#shipFreeEvent').checked=!!free;return saveShippingSettings()}
function renderVip(){const q=norm($('#vipQuery')?.value||''),rows=vipCache.filter(x=>!q||[x.nickname,x.receiver,x.phone,x.memo].some(v=>norm(v).includes(q)));$('#vipTbody').innerHTML=rows.map((x,i)=>`<tr><td><input type="checkbox" class="vipCheck" value="${x.rowNumber}"></td><td>${i+1}</td><td><b>${esc(x.nickname)}</b></td><td>${esc(x.receiver)}</td><td>${esc(x.phone)}</td><td><span class="pill ${x.taxExcluded?'green':'red'}">${x.taxExcluded?'제외':'적용'}</span></td><td><span class="pill ${x.freeShipping?'green':'orange'}">${x.freeShipping?'무료':'기본'}</span></td><td><span class="pill ${x.active?'blue':'gray'}">${x.active?'사용중':'중지'}</span></td><td><div class="mini-actions"><button class="btn ghost mini" onclick="editVip(${x.rowNumber})">수정</button><button class="btn red mini" onclick="deleteVipOne(${x.rowNumber})">삭제</button></div></td></tr>`).join('')||'<tr><td colspan="9">등록된 VIP 고객이 없습니다.</td></tr>';$('#vipCount').textContent=`전체 ${vipCache.length}명 · 현재 ${rows.length}명`;$('#vipHeaderCheck').checked=false}
async function loadVip(query=''){try{const r=await api('admin_vip_list',{query},30000);vipCache=r.rows||[];renderVip()}catch(e){toast(e.message)}}
function openVip(row=0){const x=vipCache.find(v=>v.rowNumber===Number(row))||{};$('#vipRow').value=x.rowNumber||'';$('#vipNickname').value=x.nickname||'';$('#vipReceiver').value=x.receiver||'';$('#vipPhone').value=x.phone||'';$('#vipTax').value=x.taxExcluded===false?'0':'1';$('#vipShipping').value=x.freeShipping===false?'0':'1';$('#vipActive').value=x.active===false?'0':'1';$('#vipMemo').value=x.memo||'';$('#vipModal').classList.add('show')}
window.editVip=row=>openVip(row);
async function saveVip(){try{busy(true,'VIP 고객을 저장하고 주문금액을 다시 확인하고 있습니다...');await api('admin_vip_save',{rowNumber:$('#vipRow').value,nickname:$('#vipNickname').value,receiver:$('#vipReceiver').value,phone:$('#vipPhone').value,taxExcluded:$('#vipTax').value==='1',freeShipping:$('#vipShipping').value==='1',active:$('#vipActive').value==='1',memo:$('#vipMemo').value},60000);$('#vipModal').classList.remove('show');await loadVip();await loadShippingPolicy();toast('VIP 고객을 저장했습니다.')}catch(e){toast(e.message)}finally{busy(false)}}
async function deleteVipRows(rows){if(!rows.length)return toast('삭제할 VIP 고객을 선택해주세요.');if(!confirm(rows.length+'명의 VIP 등록을 삭제할까요?'))return;try{busy(true,'VIP 목록을 정리하고 있습니다...');await api('admin_vip_delete',{rows},60000);await loadVip();await loadShippingPolicy();toast('삭제했습니다.')}catch(e){toast(e.message)}finally{busy(false)}}
window.deleteVipOne=row=>deleteVipRows([row]);
function downloadVip(){if(typeof XLSX==='undefined')return toast('엑셀 라이브러리를 불러오지 못했습니다.');const rows=vipCache.map(x=>({'닉네임':x.nickname,'수령인':x.receiver,'연락처':x.phone,'카드부가세':x.taxExcluded?'제외':'적용','배송비':x.freeShipping?'무료':'기본','상태':x.active?'사용':'중지','메모':x.memo||''})),ws=XLSX.utils.json_to_sheet(rows),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'VIP고객');XLSX.writeFile(wb,'씬느샵_VIP고객.xlsx')}
async function uploadVip(file){if(!file||typeof XLSX==='undefined')return;try{const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{cellDates:false}),ws=wb.Sheets[wb.SheetNames[0]],arr=XLSX.utils.sheet_to_json(ws,{defval:''}),rows=arr.map(r=>({nickname:r['닉네임']||r['닉네임/ID']||'',receiver:r['수령인']||r['수령인 이름']||r['이름']||'',phone:r['연락처']||r['전화번호']||'',taxExcluded:String(r['카드부가세']||r['부가세']||'제외').trim()!=='적용',freeShipping:String(r['배송비']||'무료').trim()!=='기본',active:String(r['상태']||'사용').trim()!=='중지',memo:r['메모']||''})).filter(x=>x.nickname||x.receiver||x.phone);if(!rows.length)throw new Error('VIP 고객 행을 찾지 못했습니다.');if(!confirm(rows.length+'명을 VIP 목록으로 가져올까요? 기존 VIP 목록은 이 파일 내용으로 교체됩니다.'))return;busy(true,'VIP 엑셀을 적용하고 있습니다...');await api('admin_vip_import',{rows},60000);await loadVip();await loadShippingPolicy();toast(rows.length+'명의 VIP 고객을 가져왔습니다.')}catch(e){toast(e.message)}finally{busy(false);$('#vipFile').value=''}}

/* 설정 */
async function loadSettings(){try{const r=await api('admin_settings_get'),s=r.settings;settingsLoaded=true;$('#sVersion').textContent='V'+s.version;$('#sWebApp').value=s.webAppUrl||'';$('#sVideo').value=s.youtubeVideoId||'';$('#sBankName').value=s.bankName||'';$('#sBankAccount').value=s.bankAccount||'';$('#sBankOwner').value=s.bankOwner||'';$('#sBand').value=s.bandUrl||'';$('#sChannel').value=s.channelUrl||'';$('#sPayUser').value=s.payAppUserId||'';$('#sCardProvider').value=s.cardProvider||'payapp';$('#cardProvider').value=s.cardProvider||'payapp';$('#sTossUrl').value=s.tossCardUrl||'';$('#ytStatus').textContent=s.youtubeApiConfigured?'저장됨':'미설정';$('#payStatus').textContent=s.payAppConfigured?'연결됨':'미설정'}catch(e){toast(e.message)}}
async function saveSettings(){if(!settingsLoaded)return toast('먼저 설정 불러오기를 눌러 현재 값을 확인해주세요.');const pw=$('#sPassword').value,settings={youtubeApiKey:$('#sApiKey').value,youtubeVideoId:$('#sVideo').value,bankName:$('#sBankName').value,bankAccount:$('#sBankAccount').value,bankOwner:$('#sBankOwner').value,bandUrl:$('#sBand').value,channelUrl:$('#sChannel').value,cardProvider:$('#sCardProvider').value,tossCardUrl:$('#sTossUrl').value,payAppUserId:$('#sPayUser').value,payAppLinkKey:$('#sPayKey').value,payAppLinkVal:$('#sPayVal').value,newAdminPassword:pw};try{await api('admin_settings_save',{settings});if(pw){TOKEN='';localStorage.removeItem('ssinne_admin_token');location.reload();return}toast('설정을 저장했습니다.')}catch(e){toast(e.message)}}


function switchBankTab(name){$$('[data-bank-tab]').forEach(b=>b.classList.toggle('active',b.dataset.bankTab===name));$('#bankMatchView').classList.toggle('active',name==='match');$('#bankFileView').classList.toggle('active',name==='file')}
function renderBankPreview(){if(!bankPreviewHeaders.length){$('#bankPreviewHead').innerHTML='';$('#bankPreviewBody').innerHTML='<tr><td>업로드한 파일이 없습니다.</td></tr>';return}const max=12,h=bankPreviewHeaders.slice(0,max);$('#bankPreviewHead').innerHTML='<tr>'+h.map(x=>`<th>${esc(x)}</th>`).join('')+'</tr>';$('#bankPreviewBody').innerHTML=bankPreviewRows.slice(0,300).map(r=>'<tr>'+h.map((_,i)=>`<td>${esc(r[i]??'')}</td>`).join('')+'</tr>').join('')}
function downloadBankOriginal(){if(!bankOriginalFile)return toast('업로드한 원본 파일이 없습니다.');const url=URL.createObjectURL(bankOriginalFile),a=document.createElement('a');a.href=url;a.download=bankOriginalFile.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function switchLotteTab(name){prepareLottePanel();$$('[data-lotte-tab]').forEach(b=>b.classList.toggle('active',b.dataset.lotteTab===name));$$('.lotte-view').forEach(v=>v.classList.toggle('active',v.id==='lotte-'+name))}
function lotteParams(){return{from:$('#lotteFrom').value,to:$('#lotteTo').value,query:$('#lotteQuery')?.value||'',statusMode:$('#lotteStatus').value||'전체',excludeTracked:false,excludeCombined:false}}
function validateLotteDates(){const from=$('#lotteFrom').value,to=$('#lotteTo').value;if(!from||!to){toast('조회할 시작일과 종료일을 선택해주세요.');return false}if(from>to){toast('시작일이 종료일보다 늦습니다. 날짜를 확인해주세요.');return false}return true}
function setLotteStatusMode(mode,doLoad=false){if($('#lotteStatus'))$('#lotteStatus').value=mode;$$('[data-lotte-status]').forEach(b=>b.classList.toggle('active',b.dataset.lotteStatus===mode));lotteSelected.clear();if(doLoad&&lotteLoaded)loadLotteOrders({page:1});else updateLotteHeaderCheck()}
async function loadLotteOrders(extra={}){
  try{
    prepareLottePanel();if(!validateLotteDates())return;
    if(Object.prototype.hasOwnProperty.call(extra,'page'))lottePage=Math.max(1,Number(extra.page)||1);else lottePage=1;
    busy(true,'전체주문이력에서 선택한 날짜의 주문을 50건씩 불러오고 있습니다...');
    const r=await api('admin_lotte_history_list',{...lotteParams(),page:lottePage,pageSize:lottePageSize},45000);
    lotteCache=r.rows||[];lotteTotal=Number(r.total||0);lottePage=Number(r.page||lottePage||1);lotteLoaded=true;lotteCounts=r.counts||{all:0,paid:0,unpaid:0,cardPending:0};
    $('#lAll').textContent=lotteCounts.all||0;$('#lPaid').textContent=lotteCounts.paid||0;$('#lWaiting').textContent=(Number(lotteCounts.unpaid||0)+Number(lotteCounts.cardPending||0));
    $$('[data-lotte-status]').forEach(b=>b.classList.toggle('active',b.dataset.lotteStatus===$('#lotteStatus').value));
    $('#lotteSummary').innerHTML=`${esc($('#lotteFrom').value)} ~ ${esc($('#lotteTo').value)} &nbsp; <b>총 ${Number(lotteCounts.all||0)}건</b> &nbsp; | &nbsp; 입금완료 ${Number(lotteCounts.paid||0)}건 &nbsp; | &nbsp; 미입금 ${Number(lotteCounts.unpaid||0)}건 &nbsp; | &nbsp; 카드결제대기 ${Number(lotteCounts.cardPending||0)}건`;
    renderLotteRows();
  }catch(e){toast(e.message)}finally{busy(false)}
}
function renderLotteRows(){
  const rows=lotteCache||[],pages=Math.max(1,Math.ceil(lotteTotal/lottePageSize));lottePage=Math.min(lottePage,pages);const start=(lottePage-1)*lottePageSize;
  $('#lotteTbody').innerHTML=rows.map((x,i)=>`<tr><td><input class="lotteCheck" type="checkbox" value="${esc(x.orderNo)}" ${lotteSelected.has(x.orderNo)?'checked':''}></td><td>${start+i+1}</td><td>${esc(x.date)}</td><td><b>${esc(x.orderNo)}</b></td><td>${esc(x.nickname)}</td><td>${esc(x.receiver)}</td><td>${esc(x.phone)}</td><td><b>${Number(x.qty||0)}</b></td><td><span class="pill ${statusClass(x.status)}">${esc(x.status)}</span></td><td><div class="lotte-items-cell" title="${esc(x.items||'')}">${esc((x.items||'').replace(/\n/g,' · '))}</div></td><td>${esc(x.tracking||'-')}</td></tr>`).join('')||'<tr><td colspan="11">조건에 맞는 주문이 없습니다.</td></tr>';
  $$('.lotteCheck').forEach(c=>c.onchange=()=>{c.checked?lotteSelected.add(c.value):lotteSelected.delete(c.value);updateLotteHeaderCheck();updateLotteRangeText()});
  updateLotteHeaderCheck();updateLotteRangeText();
  let html='';if(pages>1){html+=`<button ${lottePage===1?'disabled':''} onclick="goLottePage(${lottePage-1})">‹</button>`;for(let i=1;i<=pages;i++){if(pages>11&&Math.abs(i-lottePage)>4&&i!==1&&i!==pages){if(i===2||i===pages-1)html+='<span>…</span>';continue}html+=`<button class="${i===lottePage?'active':''}" onclick="goLottePage(${i})">${i}</button>`}html+=`<button ${lottePage===pages?'disabled':''} onclick="goLottePage(${lottePage+1})">›</button>`}$('#lottePager').innerHTML=html;
}
function updateLotteRangeText(){const rows=lotteCache||[],start=(lottePage-1)*lottePageSize;$('#lotteRangeText').textContent=lotteTotal?`총 ${lotteTotal}건 중 ${start+1}~${Math.min(start+rows.length,lotteTotal)}건 표시 · 선택 ${lotteSelected.size}건`:'전체 0건'}
function updateLotteHeaderCheck(){const checks=$$('.lotteCheck'),h=$('#lotteHeaderCheck');if(!h)return;h.disabled=!checks.length;h.checked=checks.length>0&&checks.every(x=>lotteSelected.has(x.value))}
function lotteModeLabel(mode){return mode==='입금완료'?'입금완료':mode==='미입금카드대기'?'미입금·카드결제대기':'전체 주문'}
async function lotteDownloadMode(mode,selectedOnly=false){
  if(!validateLotteDates())return;const orderNos=selectedOnly?[...lotteSelected]:[];if(selectedOnly&&!orderNos.length)return toast('다운로드할 주문을 체크해주세요.');
  try{const label=selectedOnly?'선택한 주문':lotteModeLabel(mode);busy(true,label+'을 롯데택배 ALPS 양식으로 정리하고 있습니다...');const r=await api('admin_lotte_history_export',{from:$('#lotteFrom').value,to:$('#lotteTo').value,statusMode:mode,orderNos,excludeTracked:false,excludeCombined:false},60000);if(!r.rows?.length)return toast('다운로드할 주문이 없습니다.');writeXlsx(r);toast(label+' '+r.orderCount+'건을 롯데택배 파일로 다운로드했습니다.')}catch(e){toast(e.message)}finally{busy(false)}
}
function renderTrackingRows(){
  const cls=x=>x.result==='매칭완료'?'green':x.result==='중복'?'blue':x.result==='확인필요'?'orange':x.result==='미매칭'?'red':'blue';
  $('#trackingTbody').innerHTML=trackingRows.map(x=>`<tr><td>${esc(x.orderNo||'-')}</td><td>${esc(x.receiver||'-')}</td><td>${esc(x.phone||'-')}</td><td><b>${esc(x.tracking)}</b></td><td>${esc(x.matchMethod||'-')}</td><td><span class="pill ${cls(x)}">${esc(x.result||'준비')}</span></td><td><div class="tracking-detail">${esc(x.detail||'')}</div>${x.matchedOrderNos?.length?`<div class="hint">연결 주문: ${esc(x.matchedOrderNos.join(', '))}</div>`:''}</td></tr>`).join('')||'<tr><td colspan="7">업로드한 송장 파일이 없습니다.</td></tr>'
}
async function combineDownload(){const keys=$$('.combineCheck:checked').map(x=>x.value);if(!keys.length)return toast('합배송 고객을 선택해주세요.');try{busy(true,'합배송 롯데택배 파일을 만드는 중입니다...');const r=await api('admin_combine_export',{from:$('#combineFrom').value,to:$('#combineTo').value,keys});if(!r.rows?.length)return toast('입금완료된 합배송 대상이 없습니다.');writeXlsx(r);toast('합배송 송장 파일을 만들었습니다.')}catch(e){toast(e.message)}finally{busy(false)}}
function showCombineCustomers(){const list=combineCache.map(g=>`<button class="customer-pop-row" onclick="this.nextElementSibling.classList.toggle('hidden')"><b>${esc(g.nickname)}</b> · ${esc(g.receiver)} <span>${g.orderCount}건 / 내품 ${g.qty}</span></button><pre class="detail-pre hidden">${esc(g.itemsText||'')}</pre>`).join('')||'<div class="note">합배송 고객이 없습니다.</div>';$('#combineCustomerList').innerHTML=list;$('#combineCustomerModal').classList.add('show')}
async function loadReturns(){try{const r=await api('admin_return_list',{query:$('#returnQuery').value,status:$('#returnStatus').value});returnCache=r.rows||[];renderReturns()}catch(e){toast(e.message)}}
function renderReturns(){$('#returnTbody').innerHTML=returnCache.map(x=>`<tr><td><input class="returnCheck" type="checkbox" value="${x.rowNumber}"></td><td><b>${esc(x.receiptNo)}</b><div class="hint">${esc(x.created)}</div></td><td>${esc(x.orderNo)}</td><td><b>${esc(x.nickname)}</b><div class="hint">${esc(x.receiver)} · ${esc(x.phone)}</div></td><td><span class="pill ${x.type==='교환'?'blue':'orange'}">${esc(x.type)}</span></td><td><details><summary>상품 보기</summary><pre class="detail-pre">${esc(x.items)}</pre></details></td><td><select id="retStatus${x.rowNumber}" class="input"><option ${x.status==='접수'?'selected':''}>접수</option><option ${x.status==='회수중'?'selected':''}>회수중</option><option ${x.status==='반품입고확인'?'selected':''}>반품입고확인</option><option ${x.status==='검수완료'?'selected':''}>검수완료</option><option ${x.status==='교환출고'?'selected':''}>교환출고</option><option ${x.status==='환불완료'?'selected':''}>환불완료</option><option ${x.status==='완료'?'selected':''}>완료</option></select></td><td><input id="retPickup${x.rowNumber}" class="input" value="${esc(x.pickupTracking)}"></td><td><input id="retExchange${x.rowNumber}" class="input" value="${esc(x.exchangeTracking)}"></td><td><button class="btn primary mini" onclick="saveReturn(${x.rowNumber})">저장</button></td></tr>`).join('')||'<tr><td colspan="10">반품·교환 접수가 없습니다.</td></tr>'}
async function createReturn(){const orderNo=$('#returnOrderNo').value.trim();if(!orderNo)return toast('원주문번호를 입력해주세요.');try{await api('admin_return_create',{orderNo,type:$('#returnType').value,reason:$('#returnReason').value});$('#returnOrderNo').value='';$('#returnReason').value='';toast('반품·교환 접수를 등록했습니다.');loadReturns()}catch(e){toast(e.message)}}
window.saveReturn=async row=>{try{await api('admin_return_update',{rowNumber:row,status:$('#retStatus'+row).value,pickupTracking:$('#retPickup'+row).value,exchangeTracking:$('#retExchange'+row).value});toast('저장했습니다.');loadReturns()}catch(e){toast(e.message)}};
async function returnLotte(mode){const rows=$$('.returnCheck:checked').map(x=>Number(x.value));if(!rows.length)return toast('반품·교환 건을 선택해주세요.');try{busy(true);const r=await api('admin_return_lotte_export',{rows,mode});if(!r.rows?.length)return toast('송장을 만들 수 있는 선택 건이 없습니다.');writeXlsx(r);toast('롯데택배 파일을 만들었습니다.')}catch(e){toast(e.message)}finally{busy(false)}}
async function loadCs(){try{const r=await api('admin_cs_list',{query:$('#csQuery').value,status:$('#csStatus').value,cardOnly:$('#csCardOnly').checked});csCache=r.rows||[];$('#csAll').textContent=r.counts.all||0;$('#csOpen').textContent=r.counts.open||0;$('#csProgress').textContent=r.counts.progress||0;$('#csDone').textContent=r.counts.done||0;$('#csHold').textContent=r.counts.hold||0;renderCs()}catch(e){toast(e.message)}}
function renderCs(){$('#csTbody').innerHTML=csCache.map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.channelId)}</td><td>${esc(x.nickname)}</td><td>${esc(x.customer)}</td><td>${esc(x.content)}</td><td>${esc(x.type)}</td><td>${esc(x.orderNo)}</td><td><span class="pill ${x.status==='완료'?'green':x.status==='진행'?'blue':x.status==='보류'?'orange':'violet'}">${esc(x.status)}</span></td><td><div class="mini-actions"><button class="btn ghost mini" onclick="csStatus(${x.rowNumber},'접수')">접수</button><button class="btn blue mini" onclick="csStatus(${x.rowNumber},'진행')">진행</button><button class="btn green mini" onclick="csStatus(${x.rowNumber},'완료')">완료</button><button class="btn ghost mini" onclick="csStatus(${x.rowNumber},'보류')">보류</button><button class="btn softpink mini" onclick="openCs(${x.rowNumber})">수정</button></div></td></tr>`).join('')||'<tr><td colspan="9">CS 내역이 없습니다.</td></tr>'}
window.csStatus=async(row,status)=>{try{await api('admin_cs_status',{rowNumber:row,status});loadCs()}catch(e){toast(e.message)}};
window.openCs=row=>{const x=csCache.find(v=>v.rowNumber===row)||{};$('#csRow').value=x.rowNumber||'';$('#csDate').value=x.date||new Date().toISOString().slice(0,10);$('#csChannelId').value=x.channelId||'';$('#csNickname').value=x.nickname||'';$('#csCustomer').value=x.customer||'';$('#csContent').value=x.content||'';$('#csType').value=x.type||'기타';$('#csEditStatus').value=x.status||'접수';$('#csOrderNo').value=x.orderNo||'';$('#csPayment').value=x.payment||'';$('#csMemo').value=x.memo||'';$('#csModal').classList.add('show')};
async function saveCs(){try{await api('admin_cs_save',{rowNumber:$('#csRow').value,date:$('#csDate').value,channelId:$('#csChannelId').value,nickname:$('#csNickname').value,customer:$('#csCustomer').value,content:$('#csContent').value,type:$('#csType').value,status:$('#csEditStatus').value,orderNo:$('#csOrderNo').value,payment:$('#csPayment').value,memo:$('#csMemo').value});$('#csModal').classList.remove('show');toast('CS를 저장했습니다.');loadCs()}catch(e){toast(e.message)}}
async function resetTodayCs(){if(!confirm('오늘 완료 처리된 CS를 접수 상태로 초기화할까요?'))return;try{const r=await api('admin_cs_reset_today_done');toast((r.updated||0)+'건을 초기화했습니다.');loadCs()}catch(e){toast(e.message)}}

function bind(){
 const on=(id,ev,fn)=>{const el=$('#'+id);if(el)el.addEventListener(ev,fn)};
 on('loginBtn','click',login);on('adminPassword','keydown',e=>{if(e.key==='Enter')login()});on('logoutBtn','click',logout);$$('.nav button').forEach(b=>b.onclick=()=>panel(b.dataset.panel));
 on('orderSearch','click',()=>{orderActiveFilter='';orderSelected.clear();loadOrders({filter:''})});$$('.kpi-btn').forEach(b=>b.onclick=()=>{const f=b.dataset.orderFilter;orderSelected.clear();loadOrders({filter:orderActiveFilter===f?'':f})});on('markPaid','click',()=>setOrderStatus('입금완료'));on('markUnpaid','click',()=>setOrderStatus('미입금'));on('markCardOrder','click',()=>setOrderStatus('카드결제'));on('markCard','click',()=>setOrderStatus('카드결제대기'));on('deleteOrders','click',deleteOrders);on('orderExport','click',exportOrders);on('lookupSearch','click',()=>loadLookup({page:1}));
 on('csSearch','click',loadCs);on('csNew','click',()=>openCs(0));on('csResetToday','click',resetTodayCs);on('csModalClose','click',()=>$('#csModal').classList.remove('show'));on('csSave','click',saveCs);$$('[data-cs-filter]').forEach(b=>b.onclick=()=>{$('#csStatus').value=b.dataset.csFilter;loadCs()});
 on('cardSearch','click',()=>loadCards('search'));on('cardShowAll','click',()=>{cardSendFilter='';loadCards('all')});$$('.card-send-filter').forEach(b=>b.onclick=()=>{const f=b.dataset.cardSendFilter||'';cardSendFilter=cardSendFilter===f?'':f;loadCards('all')});on('cardSend','click',sendCardLink);on('cardSelectAll','click',()=>{const a=$$('.cardCheck'),all=a.length&&a.every(x=>x.checked);a.forEach(x=>x.checked=!all);updateCardSelectedCount()});on('cardHeaderCheck','change',e=>{$$('.cardCheck').forEach(x=>x.checked=e.target.checked);updateCardSelectedCount()});
 on('liveLoad','click',loadLive);on('liveLinkOpen','click',()=>$('#liveLinkModal').classList.add('show'));on('liveLinkClose','click',()=>$('#liveLinkModal').classList.remove('show'));on('liveVideoSave','click',saveLiveVideo);on('bStart','click',broadcastStart);on('bCollect','click',collectLive);on('bEnd','click',broadcastEnd);
 on('productLoad','click',loadProducts);on('snapshotRefresh','click',loadSnapshots);on('pNo','input',e=>e.target.value=productCode(e.target.value));on('optionAdd','click',optionAdd);on('productSave','click',saveProduct);on('productClear','click',clearProductForm);on('productDelete','click',deleteProducts);on('productDeleteAll','click',deleteAllProducts);on('productHeaderCheck','change',e=>{$$('.productCheck').forEach(x=>x.checked=e.target.checked)});on('snapshotSave','click',saveSnapshot);on('snapshotLoadByDate','click',loadSnapshotByDate);on('giftLoad','click',loadGifts);on('giftSave','click',saveGift);on('giftApply','click',applyGifts);
 on('bankFile','change',e=>bankUpload(e.target.files[0]));on('bankStart','click',bankStartMatch);on('bankDeleteSelected','click',bankDeleteSelected);on('bankHeaderCheck','change',e=>{$$('.bankCheck').forEach(x=>x.checked=e.target.checked)});$$('.bank-filter').forEach(b=>b.onclick=()=>{bankFilter=b.dataset.bankFilter||'';bankPage=1;renderBank()});on('bankShowAll','click',()=>{bankFilter='';bankPage=1;renderBank()});on('bankRetry','click',bankReset);on('bankOriginalDownload','click',downloadBankOriginal);$$('[data-bank-tab]').forEach(b=>b.onclick=()=>switchBankTab(b.dataset.bankTab));
 on('settingsLoad','click',loadSettings);on('settingsSave','click',saveSettings);on('shippingLoad','click',async()=>{busy(true,'배송비 설정과 VIP 목록을 불러오고 있습니다...');try{await Promise.all([loadShippingPolicy(),loadVip('')])}finally{busy(false)}});on('shippingSave','click',saveShippingSettings);on('shipFreeEvent','change',()=>{});on('vipSearch','click',()=>loadVip($('#vipQuery').value));on('vipShowAll','click',()=>{$('#vipQuery').value='';loadVip('')});on('vipNew','click',()=>openVip(0));on('vipModalClose','click',()=>$('#vipModal').classList.remove('show'));on('vipSave','click',saveVip);on('vipDeleteSelected','click',()=>deleteVipRows($$('.vipCheck:checked').map(x=>Number(x.value))));on('vipHeaderCheck','change',e=>{$$('.vipCheck').forEach(x=>x.checked=e.target.checked)});on('vipDownload','click',downloadVip);on('vipUpload','click',()=>$('#vipFile').click());on('vipFile','change',e=>uploadVip(e.target.files[0]));
 $$('[data-lotte-tab]').forEach(b=>b.onclick=()=>switchLotteTab(b.dataset.lotteTab));on('lotteBuild3pl','click',rebuild3pl);on('lotteBuildSupplier','click',rebuildSupplier);
 on('lotteSearch','click',()=>{lotteSelected.clear();loadLotteOrders({page:1})});on('lotteQueryBtn','click',()=>{lotteSelected.clear();loadLotteOrders({page:1})});on('lotteQuery','keydown',e=>{if(e.key==='Enter'){lotteSelected.clear();loadLotteOrders({page:1})}});
 ['lotteFrom','lotteTo'].forEach(id=>on(id,'change',()=>{if(lotteLoaded)resetLotteResultView('날짜가 변경되었습니다. 조회하기를 눌러 새 날짜 주문을 불러오세요.')}));
 on('lotteReset','click',()=>{const today=localDateText();$('#lotteFrom').value=today;$('#lotteTo').value=today;$('#lotteQuery').value='';$('#lotteStatus').value='전체';resetLotteResultView('조회 조건을 초기화했습니다. 조회하기를 눌러주세요.');$$('[data-lotte-status]').forEach(x=>x.classList.toggle('active',x.dataset.lotteStatus==='전체'))});
 $$('[data-lotte-status]').forEach(b=>b.onclick=()=>{const hadLoaded=lotteLoaded;setLotteStatusMode(b.dataset.lotteStatus,false);if(hadLoaded)loadLotteOrders({page:1});else{$('#lotteTbody').innerHTML=`<tr><td colspan="11"><b>${esc(b.querySelector('b')?.textContent||'주문상태')}을 선택했습니다.</b><div class="hint">날짜를 확인한 뒤 조회하기를 눌러주세요.</div></td></tr>`}});
 on('lotteHeaderCheck','change',e=>{$$('.lotteCheck').forEach(x=>{x.checked=e.target.checked;e.target.checked?lotteSelected.add(x.value):lotteSelected.delete(x.value)});updateLotteHeaderCheck();updateLotteRangeText()});
 on('lottePaidDownload','click',()=>lotteDownloadMode('입금완료',false));on('lotteAllDateDownload','click',()=>lotteDownloadMode('전체',false));on('lotteWaitingDownload','click',()=>lotteDownloadMode('미입금카드대기',false));on('lotteSelectedDownload','click',()=>lotteDownloadMode('전체',true));
 on('trackingFile','change',e=>trackingRead(e.target.files[0]));on('trackingApply','click',trackingApply);on('combineSearch','click',combineSearch);on('combineHeaderCheck','change',e=>{$$('.combineCheck').forEach(x=>x.checked=e.target.checked)});on('combineDownload','click',combineDownload);on('combineCustomerPopup','click',showCombineCustomers);on('combineCustomerClose','click',()=>$('#combineCustomerModal').classList.remove('show'));
 on('returnSearch','click',loadReturns);on('returnCreate','click',createReturn);on('returnHeaderCheck','change',e=>{$$('.returnCheck').forEach(x=>x.checked=e.target.checked)});on('returnPickupDownload','click',()=>returnLotte('pickup'));on('returnExchangeDownload','click',()=>returnLotte('exchange'));
 on('pendingSearch','click',loadPending);on('pendingRefresh','click',()=>{['pendingQuery','pendingFrom','pendingTo'].forEach(id=>$('#'+id).value='');$('#pendingStatus').value='전체';pendingCache=[];$('#pendingTbody').innerHTML='<tr><td colspan="10">조건을 초기화했습니다. 조회 버튼을 눌러주세요.</td></tr>';$('#pendingCards').innerHTML=''});on('pendingLotte','click',pendingLotte);on('pendingHeaderCheck','change',e=>{$$('.pendingCheck').forEach(x=>x.checked=e.target.checked)});
 on('startClose','click',()=>$('#startModal').classList.remove('show'));$$('.startMode').forEach(b=>b.onclick=()=>broadcastStartMode(b.dataset.mode));
 on('aoEditProducts','click',()=>{adminEdit.editMode=!adminEdit.editMode;$('#aoProductEditor').classList.toggle('hidden',!adminEdit.editMode);$('#aoEditProducts').textContent=adminEdit.editMode?'수정 닫기':'상품 수정';renderAdminCart()});on('aoSearch','input',e=>renderAdminCatalog(e.target.value));on('aoSave','click',saveAdminOrder);on('aoPaid','click',()=>modalStatus('입금완료'));on('aoUnpaid','click',()=>modalStatus('미입금'));on('aoCardOrder','click',()=>modalStatus('카드결제'));on('aoCard','click',()=>modalStatus('카드결제대기'));on('aoDelete','click',modalDelete);on('orderModalClose','click',()=>$('#orderModal').classList.remove('show'));
}
document.addEventListener('DOMContentLoaded',()=>{bind();if(TOKEN)showAdmin()});

window.goLookupPage=p=>{const next=Math.max(1,Number(p)||1);if(next===lookupPage)return;loadLookup({page:next})};
window.goOrderPage=p=>{const next=Math.max(1,Number(p)||1);if(next===orderPage)return;loadOrders({page:next})};
window.goLottePage=p=>{const next=Math.max(1,Number(p)||1);if(next===lottePage)return;loadLotteOrders({page:next})};
