const API_URL=(window.SSINNE_CONFIG||{}).API_URL||'';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={catalog:[],cart:[],mode:'',nickname:'',selectedNickname:'',directNickname:'',directSuggestions:[],reservations:[],originalReservations:[],savedCustomer:null,submitToken:''};
function money(n){return Number(n||0).toLocaleString('ko-KR')+'원'}
function esc(s){return String(s==null?'':s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function api(action,payload={}){
  if(!/^https:\/\/script\.google\.com\/macros\/s\//.test(API_URL))throw new Error('config.js에 Apps Script /exec 주소를 먼저 입력해주세요.');
  const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),20000);
  try{const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload}),signal:ctrl.signal});const j=await r.json();if(!j.success)throw new Error(j.error||'처리 중 오류가 발생했습니다.');return j;}finally{clearTimeout(timer)}
}
function show(id){$$('.screen').forEach(x=>x.classList.add('hidden'));$('#'+id).classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2800)}
async function init(){
  $('#goLive').onclick=()=>{state.mode='live';show('liveScreen')};
  $('#goDirect').onclick=async()=>{state.mode='direct';show('directScreen');await ensureCatalog();renderCatalog('')};
  $('#goLookup').onclick=()=>location.href='customer.html';
  $('#liveNick').addEventListener('input',debounce(searchNick,250));$('#liveNext').onclick=livePhoneStep;$('#liveConfirm').onclick=()=>openCheckout('live');
  $('#directNick').addEventListener('input',debounce(searchDirectNick,250));$('#directLoadSaved').onclick=loadDirectSaved;$('#directPhone').addEventListener('blur',()=>{if($('#directNick').value.trim()&&$('#directPhone').value.replace(/\D/g,'').length>=10)loadDirectSaved()});$('#directSearch').addEventListener('input',e=>renderCatalog(e.target.value));$('#directSubmit').onclick=()=>submitCheckout('direct');$('#liveSubmit').onclick=()=>submitCheckout('live');
  $('#directPayment').addEventListener('change',()=>updateTotals('direct'));$('#livePayment').addEventListener('change',()=>updateTotals('live'));
  await loadPublicConfig();
}
function debounce(fn,ms){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}}
async function loadPublicConfig(){try{const c=await api('public_config');state.config=c;$('#version').textContent='V'+c.version;}catch(e){console.warn(e)}}
async function searchDirectNick(){const q=$('#directNick').value.trim(),box=$('#directNickSuggestions');box.innerHTML='';state.directNickname='';state.directSuggestions=[];if(!q)return;try{const r=await api('nickname_suggestions',{nickname:q});state.directSuggestions=r.suggestions||[];r.suggestions.forEach(n=>{const b=document.createElement('button');b.className='suggestion';b.textContent=n;b.onclick=()=>{state.directNickname=n;$('#directNick').value=n;$$('#directNickSuggestions .suggestion').forEach(x=>x.classList.remove('active'));b.classList.add('active')};box.appendChild(b)})}catch(e){}}
async function loadDirectSaved(){const nickname=state.directNickname||$('#directNick').value.trim(),phone=$('#directPhone').value.trim();if(!nickname||phone.replace(/\D/g,'').length<10)return toast('닉네임과 휴대폰 번호를 먼저 입력해주세요.');try{const r=await api('live_lookup',{nickname,phone});const s=r.savedCustomer;if(!s)return toast('저장된 배송정보가 없습니다.');$('#directReceiver').value=s.receiver||'';$('#directZip').value=s.zip||'';$('#directAddress').value=s.address||'';$('#directMemo').value=s.memo||'';toast('기존 고객 배송정보를 불러왔습니다. 주소를 확인해주세요.')}catch(e){toast(e.message)}}
async function searchNick(){const q=$('#liveNick').value.trim();const box=$('#nickSuggestions');box.innerHTML='';if(!q)return;try{const r=await api('nickname_suggestions',{nickname:q});r.suggestions.forEach(n=>{const b=document.createElement('button');b.className='suggestion';b.textContent=n;b.onclick=()=>{state.selectedNickname=n;$('#liveNick').value=n;$$('.suggestion').forEach(x=>x.classList.remove('active'));b.classList.add('active')};box.appendChild(b)})}catch(e){toast(e.message)}}
async function livePhoneStep(){
  const nickname=($('#liveNick').value||'').trim();if(!nickname)return toast('닉네임을 입력해주세요.');state.selectedNickname=state.selectedNickname||nickname;$('#liveIdentity').classList.remove('hidden');$('#livePhone').focus();
  $('#verifyPhone').onclick=async()=>{const phone=$('#livePhone').value.trim();if(phone.replace(/\D/g,'').length<10)return toast('휴대폰 번호를 입력해주세요.');try{setBusy(true,'라이브 주문을 불러오고 있습니다...');const r=await api('live_lookup',{nickname:state.selectedNickname,phone});state.reservations=(r.reservations||[]).map(x=>({...x}));state.originalReservations=(r.reservations||[]).map(x=>({...x}));state.savedCustomer=r.savedCustomer||null;renderLiveLoaded();}catch(e){toast(e.message)}finally{setBusy(false)}};
}
function renderLiveLoaded(){
  const s=state.savedCustomer;if(s){$('#liveReceiver').value=s.receiver||'';$('#liveZip').value=s.zip||'';$('#liveAddress').value=s.address||'';$('#liveMemo').value=s.memo||'';$('#savedNotice').textContent='저장된 고객정보를 불러왔습니다. 주소가 맞는지 꼭 확인해주세요.'}else{$('#savedNotice').textContent='저장된 배송지가 없습니다. 배송정보를 입력해주세요.'}
  $('#liveLoaded').classList.remove('hidden');const box=$('#liveItems');box.innerHTML='';
  if(!state.reservations.length)box.innerHTML='<div class="note">주문할 예약상품이 없습니다. 아래 버튼으로 불러온 예약을 전체 취소할 수 있습니다.</div><button type="button" class="btn red w100 section" onclick="cancelAllLoadedReservations()">불러온 예약 전체 취소</button>';
  state.reservations.forEach((x,i)=>{const d=document.createElement('div');d.className='cart-line';d.innerHTML=`<div><b>${esc(x.productNo)}번</b> / ${esc(x.color)} / ${esc(x.size)}</div><div class="qtybox"><button type="button" onclick="liveReservationQty(${i},-1)">−</button><b>${x.qty}</b><button type="button" onclick="liveReservationQty(${i},1)">+</button></div><button type="button" class="btn red" onclick="removeLiveReservation(${i})">삭제</button>`;box.appendChild(d)});$('#liveConfirm').classList.toggle('hidden',!state.reservations.length)
}
window.cancelAllLoadedReservations=async function(){if(!state.originalReservations.length)return;if(!confirm('불러온 예약을 모두 취소할까요?'))return;try{setBusy(true,'예약을 취소하고 있습니다...');const r=await api('cancel_live_reservations',{nickname:state.selectedNickname||$('#liveNick').value.trim(),messageIds:state.originalReservations.map(x=>x.messageId)});toast(r.message);state.reservations=[];state.originalReservations=[];renderLiveLoaded()}catch(e){toast(e.message)}finally{setBusy(false)}}
window.liveReservationQty=function(i,delta){const x=state.reservations[i];if(!x)return;const orig=state.originalReservations.find(o=>o.messageId===x.messageId),max=orig?orig.qty:x.qty;x.qty=Math.max(1,Math.min(max,x.qty+delta));renderLiveLoaded()}
window.removeLiveReservation=function(i){state.reservations.splice(i,1);renderLiveLoaded()}
async function ensureCatalog(){if(state.catalog.length)return;setBusy(true,'상품정보를 불러오는 중입니다...');try{const r=await api('catalog');state.catalog=r.products||[]}finally{setBusy(false)}}
function renderCatalog(q){const box=$('#directCatalog');q=String(q||'').trim().toLowerCase();const list=state.catalog.filter(p=>!q||String(p.no).includes(q)||p.name.toLowerCase().includes(q)).slice(0,40);box.innerHTML=list.map((p,i)=>`<div class="product-row"><img class="thumb" src="${esc(p.image||'')}" onerror="this.style.visibility='hidden'"><div><b>${esc(p.no)}번 · ${esc(p.name)}</b><div class="hint">${esc(p.color)} / ${esc(p.size)} · ${p.status} · 주문가능 ${p.available}개</div><div class="price">${money(p.price)}</div></div><div class="actions"><button class="btn primary" ${p.available<=0?'disabled':''} onclick="addProduct('${encodeURIComponent(p.no)}','${encodeURIComponent(p.color)}','${encodeURIComponent(p.size)}')">담기</button></div></div>`).join('')||'<div class="note">검색 결과가 없습니다.</div>'}
window.addProduct=function(no,color,size){no=decodeURIComponent(no);color=decodeURIComponent(color);size=decodeURIComponent(size);const p=state.catalog.find(x=>String(x.no)===no&&x.color===color&&x.size===size);if(!p)return;let x=state.cart.find(x=>x.productNo===p.no&&x.color===p.color&&x.size===p.size);if(x){if(x.qty>=p.available)return toast('추가 주문 가능한 수량을 초과했습니다.');x.qty++}else state.cart.push({productNo:p.no,color:p.color,size:p.size,qty:1,name:p.name,price:p.price,available:p.available,image:p.image});renderCart()}
window.cartQty=function(i,delta){const x=state.cart[i];if(!x)return;x.qty=Math.max(0,Math.min(x.available,x.qty+delta));if(!x.qty)state.cart.splice(i,1);renderCart()}
function renderCart(){const box=$('#directCart');box.innerHTML=state.cart.map((x,i)=>`<div class="cart-line"><div><b>${esc(x.productNo)}번 ${esc(x.name)}</b><div class="hint">${esc(x.color)} / ${esc(x.size)}</div></div><div class="qtybox"><button onclick="cartQty(${i},-1)">−</button><b>${x.qty}</b><button onclick="cartQty(${i},1)">+</button></div><b>${money(x.price*x.qty)}</b></div>`).join('')||'<div class="hint">상품을 검색해서 담아주세요.</div>';updateTotals('direct')}
function openCheckout(){
  if(!state.reservations.length)return toast('예약된 상품이 없습니다.');$('#liveCheckout').classList.remove('hidden');
  const s=state.savedCustomer;if(s){$('#liveReceiver').value=s.receiver||'';$('#livePhone2').value=s.phone||$('#livePhone').value;$('#liveZip').value=s.zip||'';const address=s.address||'';$('#liveAddress').value=address}else $('#livePhone2').value=$('#livePhone').value;
  updateTotals('live');window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'})
}
function getLiveCart(){return state.reservations.map(r=>{const p=state.catalog.find(x=>String(x.no)===String(r.productNo)&&x.color===r.color&&x.size===r.size);return {...r,price:p?p.price:0,name:p?p.name:''}})}
async function updateTotals(mode){if(mode==='live'&&!state.catalog.length)await ensureCatalog();const items=mode==='live'?getLiveCart():state.cart;const subtotal=items.reduce((s,x)=>s+(x.price||0)*x.qty,0),addr=(mode==='live'?$('#liveAddress').value:$('#directAddress').value)||'',ship=/제주/.test(addr)?7000:4000,method=(mode==='live'?$('#livePayment').value:$('#directPayment').value),base=subtotal+ship,total=method==='card'?Math.round(base*1.10):base;$('#'+mode+'Qty').textContent=items.reduce((s,x)=>s+x.qty,0)+'개';$('#'+mode+'Total').textContent=money(total)}
function valuesFor(mode){if(mode==='direct')return{nickname:state.directNickname||$('#directNick').value.trim(),receiver:$('#directReceiver').value.trim(),phone:$('#directPhone').value.trim(),zip:$('#directZip').value.trim(),address:$('#directAddress').value.trim(),detailAddress:$('#directDetail').value.trim(),memo:$('#directMemo').value.trim(),paymentMethod:$('#directPayment').value,items:state.cart};const choices=state.originalReservations.map(o=>{const cur=state.reservations.find(x=>x.messageId===o.messageId);return{messageId:o.messageId,qty:cur?cur.qty:0}});return{nickname:state.selectedNickname||$('#liveNick').value.trim(),receiver:$('#liveReceiver').value.trim(),phone:$('#livePhone2').value.trim(),zip:$('#liveZip').value.trim(),address:$('#liveAddress').value.trim(),detailAddress:$('#liveDetail').value.trim(),memo:$('#liveMemo').value.trim(),paymentMethod:$('#livePayment').value,items:state.reservations,reservationChoices:choices}}
async function submitCheckout(mode){if(mode==='direct'&&state.directSuggestions.length&&!state.directNickname)return toast('비슷한 라이브 닉네임이 있습니다. 닉네임을 선택해주세요.');const d=valuesFor(mode);if(!state.submitToken)state.submitToken=(window.crypto&&crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random());d.clientRequestId=state.submitToken;if(!d.nickname||!d.receiver||d.phone.replace(/\D/g,'').length<10||!d.address)return toast('배송정보를 모두 확인해주세요.');if(!d.items.length)return toast('주문상품이 없습니다.');try{setBusy(true,'주문을 저장하고 있습니다...');const r=await api('submit_order',d);state.submitToken='';renderComplete(r)}catch(e){toast(e.message)}finally{setBusy(false)}}
function renderComplete(r){show('completeScreen');$('#completeNo').textContent=r.orderNo;$('#completeInfo').innerHTML=`<div><b>주문일시</b> ${esc(r.orderDate)}</div><div><b>주문자 닉네임</b> ${esc(r.nickname)}</div><div><b>수령인</b> ${esc(r.receiver)}</div><div><b>연락처</b> ${esc(r.phone)}</div><div><b>배송지</b> ${esc(r.address)}</div><div><b>배송메시지</b> ${esc(r.memo||'-')}</div>`;$('#completeItems').innerHTML=(r.items||[]).map(x=>`<div class="cart-line"><div>${esc(x)}</div></div>`).join('');$('#completeTotal').textContent=money(r.total);const c=state.config||{},pay=$('#completePayment');if(r.paymentMethod==='무통장입금'){pay.innerHTML=`<b>무통장 입금 안내</b><br>${esc(c.bankName||'')} ${esc(c.bankAccount||'')} ${esc(c.bankOwner?(' / 예금주 '+c.bankOwner):'')} <button class="btn ghost" onclick="copyBank()">계좌번호 복사</button>`}else pay.innerHTML='<b>카드결제 선택</b><br>관리자가 확인 후 카드결제 링크를 보내드립니다.';const band=$('#bandBtn'),channel=$('#channelBtn');band.href=r.bandUrl||'#';channel.href=r.channelUrl||'#';band.classList.toggle('disabled',!r.bandUrl);channel.classList.toggle('disabled',!r.channelUrl)}
window.copyBank=async function(){const a=(state.config&&state.config.bankAccount)||'';if(!a)return toast('계좌번호가 설정되지 않았습니다.');try{await navigator.clipboard.writeText(a);toast('계좌번호를 복사했습니다.')}catch(e){toast(a)}}
window.openPostcode=function(mode){if(!window.daum||!daum.Postcode)return toast('주소검색을 불러오지 못했습니다.');new daum.Postcode({oncomplete:function(data){const addr=data.roadAddress||data.jibunAddress;if(mode==='direct'){$('#directZip').value=data.zonecode;$('#directAddress').value=addr;$('#directDetail').focus();updateTotals('direct')}else{$('#liveZip').value=data.zonecode;$('#liveAddress').value=addr;$('#liveDetail').focus();updateTotals('live')}}}).open()};
function setBusy(on,msg){const m=$('#busy');m.classList.toggle('show',on);if(msg)$('#busyText').textContent=msg}
document.addEventListener('DOMContentLoaded',init);
