const API_URL=(window.SSINNE_CONFIG||{}).API_URL||'';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={catalog:[],cart:[],reservations:[],selectedNickname:'',liveSuggestions:[],config:{},pickedProduct:null,pickQty:1,livePicked:null,livePickQty:1,submitToken:'',catalogRefreshing:false,lastOrderNo:'',catalogTs:0,catalogPromise:null};
const money=n=>Number(n||0).toLocaleString('ko-KR')+'원';
const esc=s=>String(s==null?'':s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const cleanNick=s=>String(s||'').replace(/@/g,'').trim();
async function api(action,p={},timeoutMs=12000){if(!/^https:\/\/script\.google\.com\/macros\/s\//.test(API_URL))throw new Error('config.js에 Apps Script /exec 주소를 먼저 입력해주세요.');const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeoutMs);let r;try{r=await fetch(API_URL+'?v='+Date.now(),{method:'POST',headers:{'Content-Type':'text/plain'},body:JSON.stringify({action,...p}),signal:c.signal})}catch(e){if(e&&e.name==='AbortError'){const x=new Error('서버 응답이 조금 늦어지고 있습니다. 주문 저장 여부를 확인합니다.');x.code='TIMEOUT';throw x}const x=new Error('서버 연결이 원활하지 않습니다. 잠시 후 다시 시도해주세요.');x.code='NETWORK';throw x}finally{clearTimeout(timer)}if(!r.ok)throw new Error('서버 연결 오류 ('+r.status+')');let j;try{j=JSON.parse(await r.text())}catch(e){throw new Error('서버 응답을 확인할 수 없습니다.')}if(!j.success)throw new Error(j.error||'처리 중 오류가 발생했습니다.');return j}
function toast(m){const t=$('#toast');t.textContent=m;t.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.add('hidden'),3000)}
function busy(on,m='처리 중입니다...'){$('#busy').classList.toggle('show',on);$('#busyText').textContent=m}
function show(id){$$('.screen').forEach(x=>x.classList.add('hidden'));$('#'+id).classList.remove('hidden');const home=id==='homeScreen'||id==='completeScreen';$('#backBtn').classList.toggle('hidden',home);$('#homeMenuBtn').classList.toggle('hidden',!home);scrollTo({top:0,behavior:'smooth'})}
function debounce(fn,ms){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}}
async function loadConfig(){try{state.config=await api('public_config');['directBankAccount','liveBankAccount'].forEach(id=>$('#'+id).textContent=state.config.bankAccount||'1002-5790-8378');['directBankText','liveBankText'].forEach(id=>$('#'+id).textContent=(state.config.bankName||'토스뱅크')+' - '+(state.config.bankOwner||'신성은'));renderShippingPolicy();updateTotals('direct');updateTotals('live')}catch(e){}}
function renderShippingPolicy(){const free=!!state.config.freeShippingEvent;$$('.free-badge').forEach(x=>x.textContent=free?'🚚 오늘 무료배송 이벤트 적용중':'🚚 20만원 이상 무료배송 자동계산');$$('[data-ship-target]').forEach(b=>{const isIsland=b.dataset.ship==='island',label=b.querySelector('b');if(!label)return;label.textContent=free?(isIsland?'제주 및 도서산간 (무료)':'기본배송비 (무료)'):(isIsland?'제주 및 도서산간 ('+money(state.config.islandShipping||7000)+')':'기본배송비 ('+money(state.config.shipping||4000)+')')})}
function catalogCacheKey(){return'ssinne_catalog_v621_final'}
function hydrateCatalogCache(maxAge=90000){try{const x=JSON.parse(localStorage.getItem(catalogCacheKey())||'null');if(x&&Array.isArray(x.products)&&Date.now()-Number(x.ts||0)<maxAge){state.catalog=x.products;state.catalogTs=x.ts||0;return true}}catch(e){}return false}
function storeCatalogCache(){try{localStorage.setItem(catalogCacheKey(),JSON.stringify({ts:Date.now(),products:state.catalog}))}catch(e){}}
async function fetchCatalog(force=false){if(state.catalogPromise&&!force)return state.catalogPromise;const run=api('catalog',{cacheBust:force?Date.now():0},10000).then(r=>{state.catalog=r.products||[];state.catalogTs=Date.now();storeCatalogCache();return state.catalog}).finally(()=>{state.catalogPromise=null});state.catalogPromise=run;return run}
async function ensureCatalog(){if(state.catalog.length)return state.catalog;if(hydrateCatalogCache())return state.catalog;let timer=setTimeout(()=>busy(true,'상품정보를 불러오는 중입니다...'),280);try{return await fetchCatalog(false)}finally{clearTimeout(timer);busy(false)}}
async function refreshCatalog(mode){if(state.catalogRefreshing)return;state.catalogRefreshing=true;['directCatalogRefresh','liveCatalogRefresh','liveCatalogRefresh2'].forEach(id=>{if($('#'+id))$('#'+id).disabled=true});try{busy(true,'최신 상품정보를 불러오는 중입니다...');await fetchCatalog(true);toast('상품정보를 새로고침했습니다.');if(mode==='direct'&&$('#directSearch').value)searchDirectProduct(true);if(mode==='live'&&$('#liveManualSearch').value)searchLiveManualProduct(true)}catch(e){toast(e.message)}finally{busy(false);state.catalogRefreshing=false;['directCatalogRefresh','liveCatalogRefresh','liveCatalogRefresh2'].forEach(id=>{if($('#'+id))$('#'+id).disabled=false})}}
function sanitizeNickInput(el){const v=cleanNick(el.value);if(el.value!==v)el.value=v;return v}
async function searchLiveNick(){const q=sanitizeNickInput($('#liveNick')),box=$('#nickSuggestions');box.innerHTML='';state.selectedNickname='';if(!q)return;try{const r=await api('nickname_suggestions',{nickname:q});state.liveSuggestions=r.suggestions||[];const exact=state.liveSuggestions.filter(n=>n.toLowerCase()===q.toLowerCase());if(exact.length===1)state.selectedNickname=exact[0];state.liveSuggestions.forEach(n=>{const b=document.createElement('button');b.type='button';b.className='suggestion';b.textContent=n;b.onclick=()=>{state.selectedNickname=n;$('#liveNick').value=n;box.innerHTML=''};box.appendChild(b)})}catch(e){}}
async function loadLiveOrder(){const nickname=state.selectedNickname||sanitizeNickInput($('#liveNick'));if(!nickname)return toast('닉네임을 입력해주세요.');try{busy(true,'댓글 주문을 불러오는 중입니다...');await ensureCatalog();const r=await api('live_lookup',{nickname});state.selectedNickname=nickname;state.reservations=(r.reservations||[]).map(x=>({...x}));$('#liveLoaded').classList.remove('hidden');$('#liveNick2').value=nickname;const local=getLocalShipping();if(local){$('#liveReceiver').value=local.receiver||'';$('#livePhone2').value=local.phone||'';$('#liveAddress').value=local.address||'';$('#liveDetail').value=local.detail||'';$('#liveZip').value=local.zip||'';$('#liveMemo').value=local.memo||''}renderLiveItems();updateTotals('live')}catch(e){toast(e.message)}finally{busy(false)}}
function catalogItem(it){return state.catalog.find(p=>String(p.no)===String(it.productNo)&&p.color===it.color&&p.size===it.size)}
function getLiveCart(){return state.reservations.map(r=>{const p=catalogItem(r);return{...r,name:p?.name||'',price:p?.price||0}})}
function renderLiveItems(){$('#liveItems').innerHTML=state.reservations.map((x,i)=>{const p=catalogItem(x);return`<div class="customer-item-line"><div class="item-main"><small>상품번호 ${esc(x.productNo)}</small><b>${esc(p?.name||x.productNo+'번 상품')}</b><span>칼라: ${esc(x.color)}　|　사이즈: ${esc(x.size)}　|　수량: ${x.qty}</span></div><strong>${money((p?.price||0)*x.qty)}</strong><button class="item-delete" type="button" onclick="removeLive(${i})">삭제</button></div>`}).join('')||'<div class="empty-list">불러온 댓글 주문이 없습니다. 아래에서 상품을 직접 추가할 수 있어요.</div>'}
window.removeLive=i=>{state.reservations.splice(i,1);renderLiveItems();updateTotals('live')};
function optionsForNo(no){return state.catalog.filter(p=>String(p.no)===String(no))}
function fillProductPicker(prefix,no){const opts=optionsForNo(no);if(!opts.length)return false;const nameId=prefix==='direct'?'directProductName':'liveManualName',colorId=prefix==='direct'?'directColor':'liveManualColor',sizeId=prefix==='direct'?'directSize':'liveManualSize',colorEl=$('#'+colorId),sizeEl=$('#'+sizeId),prevColor=colorEl.value,prevSize=sizeEl.value;$('#'+nameId).value=opts[0].name;const colors=[...new Set(opts.map(x=>x.color))];colorEl.innerHTML=colors.map(x=>`<option>${esc(x)}</option>`).join('');if(colors.includes(prevColor))colorEl.value=prevColor;refreshPickerSizes(prefix,no,prevSize);return true}
function refreshPickerSizes(prefix,no,preserveSize=''){const colorId=prefix==='direct'?'directColor':'liveManualColor',sizeId=prefix==='direct'?'directSize':'liveManualSize',color=$('#'+colorId).value,sizeEl=$('#'+sizeId),opts=state.catalog.filter(p=>String(p.no)===String(no)&&p.color===color),sizes=[...new Set(opts.map(x=>x.size))],keep=preserveSize||sizeEl.value;sizeEl.innerHTML=sizes.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if(sizes.includes(keep))sizeEl.value=keep;updatePickerSelection(prefix,no)}
function updatePickerSelection(prefix,no){const colorId=prefix==='direct'?'directColor':'liveManualColor',sizeId=prefix==='direct'?'directSize':'liveManualSize',p=state.catalog.find(x=>String(x.no)===String(no)&&x.color===$('#'+colorId).value&&x.size===$('#'+sizeId).value)||null;if(prefix==='direct'){state.pickedProduct=p;state.pickQty=Math.min(state.pickQty||1,Math.max(1,Number(p?.stock||1)));if($('#directQtyPick'))$('#directQtyPick').textContent=state.pickQty;if($('#directAdd'))$('#directAdd').disabled=!p||Number(p.stock||0)<=0}else{state.livePicked=p;state.livePickQty=Math.min(state.livePickQty||1,Math.max(1,Number(p?.stock||1)));if($('#liveManualQty'))$('#liveManualQty').textContent=state.livePickQty;if($('#liveManualAdd'))$('#liveManualAdd').disabled=!p||Number(p.stock||0)<=0}}
async function searchDirectProduct(skip){try{await ensureCatalog()}catch(e){toast(e.message);return}const no=$('#directSearch').value.replace(/\D/g,'');$('#directSearch').value=no;if(!no)return toast('상품번호를 입력해주세요.');let ok=fillProductPicker('direct',no);if(!ok&&!skip){await refreshCatalog('');ok=fillProductPicker('direct',no)}if(!ok){$('#directProductBox').classList.add('hidden');return toast('상품정보를 찾지 못했습니다.')}$('#directProductBox').classList.remove('hidden');state.pickQty=1;$('#directQtyPick').textContent='1'}
async function searchLiveManualProduct(skip){try{await ensureCatalog()}catch(e){toast(e.message);return}const no=$('#liveManualSearch').value.replace(/\D/g,'');$('#liveManualSearch').value=no;if(!no)return toast('상품번호를 입력해주세요.');let ok=fillProductPicker('liveManual',no);if(!ok&&!skip){await refreshCatalog('');ok=fillProductPicker('liveManual',no)}if(!ok){$('#liveManualBox').classList.add('hidden');return toast('상품정보를 찾지 못했습니다.')}$('#liveManualBox').classList.remove('hidden');state.livePickQty=1;$('#liveManualQty').textContent='1'}
function addPickedProduct(){const p=state.pickedProduct;if(!p)return toast('상품을 먼저 검색해주세요.');if(Number(p.stock||0)<=0)return toast('현재 주문가능수량이 없습니다.');if(state.pickQty>Number(p.stock||0))return toast('주문가능수량은 '+p.stock+'개입니다.');let x=state.cart.find(x=>String(x.productNo)===String(p.no)&&x.color===p.color&&x.size===p.size),already=x?Number(x.qty||0):0;if(already+state.pickQty>Number(p.stock||0))return toast('장바구니 포함 주문가능수량은 '+p.stock+'개입니다.');if(x)x.qty+=state.pickQty;else state.cart.push({productNo:p.no,name:p.name,color:p.color,size:p.size,qty:state.pickQty,price:p.price});renderDirectCart();updateTotals('direct');toast('상품을 담았습니다.')}
function addLivePicked(){const p=state.livePicked;if(!p)return toast('상품을 먼저 검색해주세요.');if(Number(p.stock||0)<=0)return toast('현재 주문가능수량이 없습니다.');if(state.livePickQty>Number(p.stock||0))return toast('주문가능수량은 '+p.stock+'개입니다.');let x=state.reservations.find(x=>String(x.productNo)===String(p.no)&&x.color===p.color&&x.size===p.size),already=x?Number(x.qty||0):0;if(already+state.livePickQty>Number(p.stock||0))return toast('주문에 담긴 수량 포함 주문가능수량은 '+p.stock+'개입니다.');if(x)x.qty+=state.livePickQty;else state.reservations.push({productNo:p.no,color:p.color,size:p.size,qty:state.livePickQty,messageId:''});renderLiveItems();updateTotals('live');toast('주문에 추가했습니다.')}
function renderDirectCart(){$('#directCart').innerHTML=state.cart.map((x,i)=>`<div class="customer-item-line"><div class="item-main"><small>상품번호 ${esc(x.productNo)}</small><b>${esc(x.name)}</b><span>칼라: ${esc(x.color)}　|　사이즈: ${esc(x.size)}　|　수량: ${x.qty}</span></div><strong>${money(x.price*x.qty)}</strong><button class="item-delete" onclick="removeDirect(${i})">⌫</button></div>`).join('')||'<div class="empty-list">상품을 검색해서 담아주세요.</div>'}
window.removeDirect=i=>{state.cart.splice(i,1);renderDirectCart();updateTotals('direct')};
function selectPayment(mode,val){$('#'+mode+'Payment').value=val;$$(`[data-pay-target="${mode}"]`).forEach(b=>{b.classList.toggle('active',b.dataset.pay===val);const s=b.querySelector('span');if(s)s.textContent=b.classList.contains('active')?'◉':'○'});updateTotals(mode)}
function selectShipping(mode,val){$('#'+mode+'ShippingType').value=val;$$(`[data-ship-target="${mode}"]`).forEach(b=>{b.classList.toggle('active',b.dataset.ship===val);const s=b.querySelector('span');if(s)s.textContent=b.classList.contains('active')?'◉':'○'});updateTotals(mode)}
function getItems(mode){return mode==='live'?getLiveCart():state.cart}
function updateTotals(mode){const subtotal=getItems(mode).reduce((s,x)=>s+Number(x.price||0)*Number(x.qty||0),0),free=!!state.config.freeShippingEvent,threshold=Number(state.config.freeShippingThreshold||200000),basic=Number(state.config.shipping??4000),island=Number(state.config.islandShipping??7000),ship=free||subtotal>=threshold?0:($('#'+mode+'ShippingType').value==='island'?island:basic),base=subtotal+ship,total=$('#'+mode+'Payment').value==='card'?Math.round(base*(1+Number(state.config.cardExtraRate??0.10))):base;$('#'+mode+'Subtotal').textContent=money(subtotal);$('#'+mode+'Shipping').textContent=ship?money(ship):'무료배송';$('#'+mode+'Total').textContent=money(total)}
function valuesFor(mode){if(mode==='direct')return{orderSource:'직접입력',nickname:sanitizeNickInput($('#directNick')),receiver:$('#directReceiver').value.trim(),phone:$('#directPhone').value.trim(),zip:$('#directZip').value,address:$('#directAddress').value.trim(),detailAddress:$('#directDetail').value.trim(),memo:$('#directMemo').value.trim(),paymentMethod:$('#directPayment').value,shippingType:$('#directShippingType').value,items:state.cart};return{orderSource:'불러오기',nickname:cleanNick(state.selectedNickname||$('#liveNick').value),receiver:$('#liveReceiver').value.trim(),phone:$('#livePhone2').value.trim(),zip:$('#liveZip').value,address:$('#liveAddress').value.trim(),detailAddress:$('#liveDetail').value.trim(),memo:$('#liveMemo').value.trim(),paymentMethod:$('#livePayment').value,shippingType:$('#liveShippingType').value,items:state.reservations}}
function applyLocalAvailability(items){(items||[]).forEach(it=>{const p=state.catalog.find(x=>String(x.no)===String(it.productNo)&&x.color===it.color&&x.size===it.size);if(p)p.stock=Math.max(0,Number(p.stock||0)-Number(it.qty||0));});storeCatalogCache()}
async function submitCheckout(mode){const d=valuesFor(mode),btn=$("#"+mode+"Submit");if(!d.nickname||!d.receiver||d.phone.replace(/\D/g,"").length<10||!d.address)return toast("배송지 정보를 모두 입력해주세요.");if(!d.items.length)return toast("주문상품이 없습니다.");for(const it of d.items){const p=state.catalog.find(x=>String(x.no)===String(it.productNo)&&x.color===it.color&&x.size===it.size);if(!p)return toast(it.productNo+"번 상품정보를 다시 검색해주세요.");if(Number(it.qty||0)>Number(p.stock||0))return toast(it.productNo+"번 "+it.color+" "+it.size+" 주문가능수량은 "+p.stock+"개입니다.")}saveLocalShipping(mode);if(!state.submitToken)state.submitToken=(crypto?.randomUUID?.()||Date.now()+"-"+Math.random());d.clientRequestId=state.submitToken;if(btn){btn.disabled=true;btn.dataset.oldText=btn.textContent;btn.textContent="주문서 전송 중...";}try{busy(true,"주문서 전송 중입니다. 잠시만 기다려주세요.");let r;try{r=await api("submit_order",d,16000)}catch(e){if(e.code!=="TIMEOUT")throw e;for(let i=0;i<4&&!r;i++){if($("#busyText"))$("#busyText").textContent="주문 저장 여부를 확인하고 있습니다… ("+(i+1)+"/4)";await new Promise(x=>setTimeout(x,1400+i*600));try{const chk=await api("request_status",{clientRequestId:state.submitToken},7000);if(chk&&chk.found)r=chk;}catch(_){}}}if(!r||!r.success){const x=new Error("주문서 제출을 확인하지 못했습니다. 입력내용은 그대로 유지됩니다. 다시 제출 버튼을 눌러주세요.");x.code="NOT_CONFIRMED";throw x;}state.submitToken="";applyLocalAvailability(d.items);renderComplete(r);api("post_submit_sync",{orderNo:r.orderNo},12000).catch(()=>{})}catch(e){toast(e.message||"주문서 제출에 실패했습니다. 다시 시도해주세요.")}finally{busy(false);if(btn){btn.disabled=false;btn.textContent=btn.dataset.oldText||"제출하기";}}}
function renderComplete(r){state.lastOrderNo=r.orderNo||"";show("completeScreen");$("#completeNo").textContent=r.orderNo||"";$("#completeCount").textContent=r.totalQty||((r.items||[]).length);const info=[["▣","주문일시",r.orderDate],["●","주문자 닉네임",r.nickname],["●","수령인",r.receiver],["☎","연락처",r.phone],["⌖","배송지",r.address],["▤","배송메시지",r.memo||"-"],["💳","결제수단",r.paymentMethod||"-"],["₩","결제금액",money(r.total||0)]];$("#completeInfo").innerHTML=info.map(x=>`<div class="complete-info-row"><span class="info-icon">${x[0]}</span><b>${x[1]}</b><em>${esc(x[2])}</em></div>`).join("");$("#completeItems").innerHTML=(r.items||[]).map(x=>`<div class="complete-item-line"><span>${esc(x)}</span></div>`).join("");$("#completeTotal").textContent=money(r.total);$("#bandBtn").href=r.bandUrl||state.config.bandUrl;$("#channelBtn").href=r.channelUrl||state.config.channelUrl}
function saveLocalShipping(mode='direct'){const p=mode==='live'?'live':'direct',v={nickname:p==='live'?cleanNick($('#liveNick2').value):sanitizeNickInput($('#directNick')),receiver:$('#'+p+'Receiver').value||'',phone:$('#'+p+'Phone'+(p==='live'?'2':'')).value||'',address:$('#'+p+'Address').value||'',detail:$('#'+p+'Detail').value||'',zip:$('#'+p+'Zip').value||'',memo:$('#'+p+'Memo').value||''};localStorage.setItem('ssinne_shipping',JSON.stringify(v))}
function getLocalShipping(){try{return JSON.parse(localStorage.getItem('ssinne_shipping')||'null')}catch(e){return null}}
function restoreLocalShipping(){const v=getLocalShipping();if(!v)return;$('#directNick').value=cleanNick(v.nickname);$('#directReceiver').value=v.receiver||'';$('#directPhone').value=v.phone||'';$('#directAddress').value=v.address||'';$('#directDetail').value=v.detail||'';$('#directZip').value=v.zip||'';$('#directMemo').value=v.memo||''}
async function init(){
 $('#goLive').onclick=async()=>{show('liveScreen');loadConfig();try{await ensureCatalog()}catch(e){}};$('#goDirect').onclick=async()=>{show('directScreen');loadConfig();try{await ensureCatalog()}catch(e){}restoreLocalShipping()};$('#backBtn').onclick=()=>show('homeScreen');
 $('#liveNick').addEventListener('input',debounce(searchLiveNick,220));$('#liveNick').addEventListener('paste',()=>setTimeout(()=>sanitizeNickInput($('#liveNick')),0));$('#liveLoad').onclick=loadLiveOrder;$('#directNick').addEventListener('input',e=>sanitizeNickInput(e.target));$('#directNick').addEventListener('paste',()=>setTimeout(()=>sanitizeNickInput($('#directNick')),0));
 $('#directSearch').addEventListener('input',e=>e.target.value=e.target.value.replace(/\D/g,''));$('#directSearchBtn').onclick=()=>searchDirectProduct(false);$('#directSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();searchDirectProduct(false)}});$('#directCatalogRefresh').onclick=()=>refreshCatalog('direct');$('#liveCatalogRefresh').onclick=()=>refreshCatalog('live');$('#liveCatalogRefresh2').onclick=()=>refreshCatalog('live');
 $('#directColor').onchange=()=>refreshPickerSizes('direct',$('#directSearch').value);$('#directSize').onchange=()=>updatePickerSelection('direct',$('#directSearch').value);$('#directMinus').onclick=()=>{state.pickQty=Math.max(1,state.pickQty-1);$('#directQtyPick').textContent=state.pickQty};$('#directPlus').onclick=()=>{const m=Math.max(1,Number(state.pickedProduct?.stock||1));state.pickQty=Math.min(m,state.pickQty+1);$('#directQtyPick').textContent=state.pickQty};$('#directAdd').onclick=addPickedProduct;
 $('#liveManualSearch').addEventListener('input',e=>e.target.value=e.target.value.replace(/\D/g,''));$('#liveManualSearchBtn').onclick=()=>searchLiveManualProduct(false);$('#liveManualColor').onchange=()=>refreshPickerSizes('liveManual',$('#liveManualSearch').value);$('#liveManualSize').onchange=()=>updatePickerSelection('liveManual',$('#liveManualSearch').value);$('#liveManualMinus').onclick=()=>{state.livePickQty=Math.max(1,state.livePickQty-1);$('#liveManualQty').textContent=state.livePickQty};$('#liveManualPlus').onclick=()=>{const m=Math.max(1,Number(state.livePicked?.stock||1));state.livePickQty=Math.min(m,state.livePickQty+1);$('#liveManualQty').textContent=state.livePickQty};$('#liveManualAdd').onclick=addLivePicked;
 $$('.simple-choice[data-pay-target]').forEach(b=>b.onclick=()=>selectPayment(b.dataset.payTarget,b.dataset.pay));$$('.simple-choice[data-ship-target]').forEach(b=>b.onclick=()=>selectShipping(b.dataset.shipTarget,b.dataset.ship));$('#directSubmit').onclick=()=>submitCheckout('direct');$('#liveSubmit').onclick=()=>submitCheckout('live');$('#completeCopy').onclick=copyOrderNo;hydrateCatalogCache();loadConfig();setInterval(()=>loadConfig(),45000);if(!state.catalog.length)fetchCatalog(false).catch(()=>{})
}
document.addEventListener('DOMContentLoaded',init);
