const API_URL=(window.SSINNE_CONFIG||{}).API_URL||'';
const $=s=>document.querySelector(s), esc=s=>String(s==null?'':s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),money=n=>Number(n||0).toLocaleString('ko-KR')+'원';
const state={orders:[],catalog:[],edit:null,editCart:[],originalQty:{},authReceiver:'',authPhone:'',config:{}};
async function api(action,p={}){
  if(!/^https:\/\/script\.google\.com\/macros\/s\//.test(API_URL)) throw new Error('주문조회 서버 주소가 설정되지 않았습니다.');
  let r;
  try{
    r=await fetch(API_URL+'?v='+Date.now(),{method:'POST',headers:{'Content-Type':'text/plain'},body:JSON.stringify({action,...p})});
  }catch(err){
    console.error('Customer API network error',err);
    throw new Error('서버 연결이 원활하지 않습니다. 잠시 후 다시 시도해주세요.');
  }
  if(!r.ok) throw new Error('서버 연결 오류가 발생했습니다. ('+r.status+')');
  let j;
  try{j=JSON.parse(await r.text())}catch(err){throw new Error('서버 응답을 확인할 수 없습니다. 잠시 후 다시 시도해주세요.')}
  if(!j.success) throw new Error(j.error||'처리 오류');
  return j;
}
function key(x){return [String(x.productNo||''),String(x.color||'').trim().toLowerCase(),String(x.size||'').trim().toLowerCase()].join('|')}
async function loadConfig(){try{const r=await api('public_config');state.config=r||{}}catch(e){}}
async function lookup(){const receiver=$('#receiver').value.trim(),phoneLast4=$('#last4').value.trim();if(!receiver||phoneLast4.replace(/\D/g,'').length!==4)return msg('수령인 성함과 연락처 뒤 4자리를 입력해주세요.');try{busy(true,'주문을 조회하고 있습니다...');const r=await api('customer_lookup',{receiver,phoneLast4});state.orders=r.orders||[];render(state.orders)}catch(e){msg(e.message)}finally{busy(false)}}
function render(orders){$('#result').classList.remove('hidden');$('#count').textContent=`총 ${orders.length}건`;$('#orders').innerHTML=orders.map(o=>{const statusClass=o.status==='입금완료'?'green':o.status==='미입금'?'gray':'blue';let actions='';if(o.canEdit){actions=`<div class="toolbar section"><button class="btn softpink" onclick="openEdit('${esc(o.orderNo)}')">✎ 주문수정</button><button class="btn red" onclick="openEdit('${esc(o.orderNo)}')">⌫ 주문삭제</button></div><div class="edit-tip">아직 입금 전이에요. 아래에서 직접 수정 또는 삭제할 수 있어요. ♡</div>`}else if(o.source==='current'&&o.status==='입금완료'){const ch=state.config.channelUrl?`<a class="btn ghost" target="_blank" href="${esc(state.config.channelUrl)}">◌ 채널톡 문의</a>`:'';actions=`<div class="toolbar section">${ch}</div><div class="note section">입금완료된 주문은 고객이 직접 수정·삭제할 수 없습니다. 관리자에게 문의해주세요.</div>`}const pend=o.pending?`<div class="pending-customer-card"><div class="pending-customer-title"><b>📦 미출고 안내</b><span class="pill red">미출고</span></div><div><strong>${esc(o.pending.reason||'상품 준비 중입니다.')}</strong></div>${o.pending.expectedDate?`<div class="pending-date-line">예상출고일 <b>${esc(o.pending.expectedDate)}</b></div>`:''}</div>`:'';return `<div class="order-card ${o.canEdit?'unpaid':''}"><div class="order-head"><div><div class="hint">주문번호</div><b style="font-size:18px">${esc(o.orderNo)}</b></div><div style="text-align:right"><div class="hint">${esc(o.date)}</div><span class="pill ${statusClass}">${esc(o.status)}</span></div></div><div class="order-lines"><span class="hint">구매내역</span><br>${esc(o.items)}</div>${pend}<div class="section-title section"><b style="font-size:19px">${money(o.amount)}</b><div>${o.tracking?`<button class="btn primary" onclick="track('${esc(o.tracking)}')">배송조회 ↗</button>`:'<span class="pill gray">상품준비중</span>'}</div></div>${actions}</div>`}).join('')||'<div class="note section">조회된 주문이 없습니다.</div>'}
window.openEdit=function(orderNo){const o=state.orders.find(x=>x.orderNo===orderNo&&x.source==='current');if(!o||!o.canEdit)return msg('이 주문은 고객이 수정할 수 없습니다.');state.edit={orderNo};state.authReceiver=$('#receiver').value.trim();state.authPhone='';$('#editOrderNo').textContent='주문번호 '+orderNo;$('#editPhone').value='';$('#editVerify').classList.remove('hidden');$('#editForm').classList.add('hidden');$('#editModal').classList.add('show');setTimeout(()=>$('#editPhone').focus(),100)}
async function verifyEdit(){const phone=$('#editPhone').value.trim();if(phone.replace(/\D/g,'').length<10)return msg('전체 휴대폰번호를 입력해주세요.');try{busy(true,'본인정보를 확인하고 있습니다...');const r=await api('customer_order_detail',{orderNo:state.edit.orderNo,authReceiver:state.authReceiver,phone});const o=r.order;if(!o.canEdit)throw new Error('입금완료된 주문은 관리자만 수정할 수 있습니다.');state.edit=o;state.authPhone=phone;state.editCart=(o.editItems||[]).map(x=>({...x}));state.originalQty={};state.editCart.forEach(x=>state.originalQty[key(x)]=(state.originalQty[key(x)]||0)+Number(x.qty||0));$('#editReceiver').value=o.receiver||'';$('#editZip').value=o.zip||'';$('#editAddress').value=o.address||'';$('#editMemo').value=o.memo||'';$('#editVerify').classList.add('hidden');$('#editForm').classList.remove('hidden');await ensureCatalog();renderEditCart();renderEditCatalog('')}catch(e){msg(e.message)}finally{busy(false)}}
async function ensureCatalog(){if(state.catalog.length)return;const r=await api('catalog');state.catalog=r.products||[]}
function renderEditCart(){const box=$('#editCart');box.innerHTML=state.editCart.map((x,i)=>`<div class="cart-line"><div><b>${esc(x.productNo)}번 ${esc(x.name||'')}</b><div class="hint">${esc(x.color)} / ${esc(x.size)}</div></div><div class="qtybox"><button type="button" onclick="editQty(${i},-1)">−</button><b>${x.qty}</b><button type="button" onclick="editQty(${i},1)">+</button></div><button class="btn red" type="button" onclick="removeEditItem(${i})">삭제</button></div>`).join('')||'<div class="note">상품을 모두 삭제하려면 아래의 ‘주문 삭제’ 버튼을 사용해주세요.</div>';updateEditAmount()}
window.editQty=function(i,delta){const x=state.editCart[i];if(!x)return;const p=state.catalog.find(p=>String(p.no)===String(x.productNo)&&p.color===x.color&&p.size===x.size),max=Math.max(Number(x.qty||1),Number((p&&p.stock)||0)+Number(state.originalQty[key(x)]||0));x.qty=Math.max(1,Math.min(max,Number(x.qty||1)+delta));renderEditCart()}
window.removeEditItem=function(i){state.editCart.splice(i,1);renderEditCart()}
function renderEditCatalog(q){q=String(q||'').trim().toLowerCase();const list=state.catalog.filter(p=>!q||String(p.no).includes(q)||String(p.name||'').toLowerCase().includes(q)).slice(0,30);$('#editCatalog').innerHTML=list.map(p=>`<div class="product-row"><div><b>${esc(p.no)}번 · ${esc(p.name)}</b><div class="hint">${esc(p.color)} / ${esc(p.size)} · 현재재고 ${p.stock}개</div><div class="price">${money(p.price)}</div></div><div></div><button class="btn primary" type="button" onclick="addEditProduct('${encodeURIComponent(p.no)}','${encodeURIComponent(p.color)}','${encodeURIComponent(p.size)}')">담기</button></div>`).join('')||'<div class="hint">검색 결과가 없습니다.</div>'}
window.addEditProduct=function(no,color,size){no=decodeURIComponent(no);color=decodeURIComponent(color);size=decodeURIComponent(size);const p=state.catalog.find(x=>String(x.no)===String(no)&&x.color===color&&x.size===size);if(!p)return;let x=state.editCart.find(x=>String(x.productNo)===String(p.no)&&x.color===p.color&&x.size===p.size);const max=Number(p.stock||0)+Number(state.originalQty[key({productNo:p.no,color:p.color,size:p.size})]||0);if(x){if(x.qty>=Math.max(1,max))return msg('추가 주문 가능한 수량을 초과했습니다.');x.qty++}else{if(max<=0)return msg('현재 추가 가능한 재고가 없습니다.');state.editCart.push({productNo:p.no,name:p.name,color:p.color,size:p.size,qty:1,price:p.price})}renderEditCart()}
function updateEditAmount(){const subtotal=state.editCart.reduce((s,x)=>s+Number(x.price||0)*Number(x.qty||0),0);$('#editAmount').textContent=money(subtotal)+' + 기존 배송비/카드조건' }
async function saveEdit(){if(!state.editCart.length)return msg('상품을 모두 없애려면 주문 삭제를 눌러주세요.');const receiver=$('#editReceiver').value.trim(),address=$('#editAddress').value.trim();if(!receiver||!address)return msg('수령인과 주소를 확인해주세요.');try{busy(true,'주문을 수정하고 있습니다...');const r=await api('customer_update_order',{orderNo:state.edit.orderNo,authReceiver:state.authReceiver,phone:state.authPhone,receiver,zip:$('#editZip').value.trim(),address,memo:$('#editMemo').value.trim(),items:state.editCart});msg(r.message||'수정했습니다.');closeEdit();await lookup()}catch(e){msg(e.message)}finally{busy(false)}}
async function deleteEdit(){if(!confirm('이 주문을 삭제할까요?\n삭제 후 재고 반영은 시스템 처리 기준에 따라 적용됩니다.'))return;try{busy(true,'주문을 삭제하고 있습니다...');const r=await api('customer_delete_order',{orderNo:state.edit.orderNo,authReceiver:state.authReceiver,phone:state.authPhone});msg(r.message||'삭제했습니다.');closeEdit();await lookup()}catch(e){msg(e.message)}finally{busy(false)}}
function closeEdit(){$('#editModal').classList.remove('show');state.edit=null;state.editCart=[]}
window.track=function(tracking){const url='https://www.lotteglogis.com/home/reservation/tracking/linkView?InvNo='+encodeURIComponent(tracking);window.open(url,'_blank')}
function msg(t){$('#msg').textContent=t;$('#msg').classList.remove('hidden');setTimeout(()=>$('#msg').classList.add('hidden'),3500)}
function busy(on,text){$('#busy').classList.toggle('show',on);if(text)$('#busyText').textContent=text}
function openPostcode(){if(!window.daum||!daum.Postcode)return msg('주소검색을 불러오지 못했습니다.');new daum.Postcode({oncomplete:d=>{$('#editZip').value=d.zonecode;$('#editAddress').value=d.roadAddress||d.jibunAddress}}).open()}
document.addEventListener('DOMContentLoaded',()=>{loadConfig();$('#lookup').onclick=lookup;$('#editVerifyBtn').onclick=verifyEdit;$('#editSave').onclick=saveEdit;$('#editDelete').onclick=deleteEdit;$('#editClose').onclick=closeEdit;$('#editCancel').onclick=closeEdit;$('#editPostcode').onclick=openPostcode;$('#editSearch').addEventListener('input',e=>renderEditCatalog(e.target.value));$('#editModal').onclick=e=>{if(e.target.id==='editModal')closeEdit()}});
